"""Generated by atdpy from type definitions in boundary.atd.

This implements classes for the types defined in 'boundary.atd', providing
methods and functions to convert data from/to JSON.
"""

# Disable flake8 entirely on this file:
# flake8: noqa

# Import annotations to allow forward references
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, NoReturn, Optional, Tuple, Union

import json

############################################################################
# Private functions
############################################################################


def _atd_missing_json_field(type_name: str, json_field_name: str) -> NoReturn:
    raise ValueError(f"missing field '{json_field_name}'"
                     f" in JSON object of type '{type_name}'")


def _atd_bad_json(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible JSON value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_bad_python(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible Python value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_read_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_json('unit', x)


def _atd_read_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_json('bool', x)


def _atd_read_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_json('int', x)


def _atd_read_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_json('float', x)


def _atd_read_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_json('str', x)


def _atd_read_list(
            read_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def read_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [read_elt(elt) for elt in elts]
        else:
            _atd_bad_json('array', elts)
    return read_list


def _atd_read_assoc_array_into_dict(
            read_key: Callable[[Any], Any],
            read_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[Any, Any]]:
    def read_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {read_key(elt[0]): read_value(elt[1]) for elt in elts}
        else:
            _atd_bad_json('array', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_dict(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def read_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_read_string(k): read_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_list(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], List[Tuple[str, Any]]]:
    def read_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(_atd_read_string(k), read_value(v))
                    for k, v in elts.items()]
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_nullable(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return read_elt(x)
    return read_nullable


def _atd_read_option(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_option(x: Any) -> Any:
        if x == 'None':
            return None
        elif isinstance(x, List) and len(x) == 2 and x[0] == 'Some':
            return read_elt(x[1])
        else:
            _atd_bad_json('option', x)
            raise AssertionError('impossible')  # keep mypy happy
    return read_option


def _atd_write_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_python('unit', x)


def _atd_write_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_python('bool', x)


def _atd_write_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_python('int', x)


def _atd_write_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_python('float', x)


def _atd_write_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_python('str', x)


def _atd_write_list(
            write_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def write_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [write_elt(elt) for elt in elts]
        else:
            _atd_bad_python('list', elts)
    return write_list


def _atd_write_assoc_dict_to_array(
            write_key: Callable[[Any], Any],
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[Any, Any]], List[Tuple[Any, Any]]]:
    def write_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(write_key(k), write_value(v)) for k, v in elts.items()]
        else:
            _atd_bad_python('Dict[str, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_dict_to_object(
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def write_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_write_string(k): write_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_python('Dict[str, <value type>]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_list_to_object(
            write_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[str, Any]]:
    def write_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {_atd_write_string(elt[0]): write_value(elt[1])
                    for elt in elts}
        else:
            _atd_bad_python('List[Tuple[<key type>, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_nullable(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return write_elt(x)
    return write_nullable


def _atd_write_option(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_option(x: Any) -> Any:
        if x is None:
            return 'None'
        else:
            return ['Some', write_elt(x)]
    return write_option


############################################################################
# Public classes
############################################################################


@dataclass
class Effective:
    """Original type: tax_rate_source = [ ... | Effective | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Effective'

    @staticmethod
    def to_json() -> Any:
        return 'Effective'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Statutory:
    """Original type: tax_rate_source = [ ... | Statutory | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Statutory'

    @staticmethod
    def to_json() -> Any:
        return 'Statutory'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class TaxRateSource:
    """Original type: tax_rate_source = [ ... ]
    """

    value: Union[Effective, Statutory]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'TaxRateSource':
        if isinstance(x, str):
            if x == 'Effective':
                return cls(Effective())
            if x == 'Statutory':
                return cls(Statutory())
            _atd_bad_json('TaxRateSource', x)
        _atd_bad_json('TaxRateSource', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'TaxRateSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Ok:
    """Original type: status = [ ... | Ok | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Ok'

    @staticmethod
    def to_json() -> Any:
        return 'Ok'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Failed:
    """Original type: status = [ ... | Failed | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Failed'

    @staticmethod
    def to_json() -> Any:
        return 'Failed'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Status:
    """Original type: status = [ ... ]
    """

    value: Union[Ok, Failed]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'Status':
        if isinstance(x, str):
            if x == 'Ok':
                return cls(Ok())
            if x == 'Failed':
                return cls(Failed())
            _atd_bad_json('Status', x)
        _atd_bad_json('Status', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'Status':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Buy:
    """Original type: signal = [ ... | Buy | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Buy'

    @staticmethod
    def to_json() -> Any:
        return 'Buy'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Hold:
    """Original type: signal = [ ... | Hold | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Hold'

    @staticmethod
    def to_json() -> Any:
        return 'Hold'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Sell:
    """Original type: signal = [ ... | Sell | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Sell'

    @staticmethod
    def to_json() -> Any:
        return 'Sell'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Signal:
    """Original type: signal = [ ... ]
    """

    value: Union[Buy, Hold, Sell]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'Signal':
        if isinstance(x, str):
            if x == 'Buy':
                return cls(Buy())
            if x == 'Hold':
                return cls(Hold())
            if x == 'Sell':
                return cls(Sell())
            _atd_bad_json('Signal', x)
        _atd_bad_json('Signal', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'Signal':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Parameter:
    """Original type: parameter = { ... }
    """

    value: float
    key: str
    source: str
    as_of: str
    age_days: int
    estimated: bool = field(default_factory=lambda: False)

    @classmethod
    def from_json(cls, x: Any) -> 'Parameter':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_float(x['value']) if 'value' in x else _atd_missing_json_field('Parameter', 'value'),
                key=_atd_read_string(x['key']) if 'key' in x else _atd_missing_json_field('Parameter', 'key'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Parameter', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Parameter', 'as_of'),
                age_days=_atd_read_int(x['age_days']) if 'age_days' in x else _atd_missing_json_field('Parameter', 'age_days'),
                estimated=_atd_read_bool(x['estimated']) if 'estimated' in x else False,
            )
        else:
            _atd_bad_json('Parameter', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_float(self.value)
        res['key'] = _atd_write_string(self.key)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['age_days'] = _atd_write_int(self.age_days)
        res['estimated'] = _atd_write_bool(self.estimated)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Parameter':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Generic:
    """Original type: model = [ ... | Generic | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Generic'

    @staticmethod
    def to_json() -> Any:
        return 'Generic'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Bank:
    """Original type: model = [ ... | Bank | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Bank'

    @staticmethod
    def to_json() -> Any:
        return 'Bank'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Insurer:
    """Original type: model = [ ... | Insurer | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Insurer'

    @staticmethod
    def to_json() -> Any:
        return 'Insurer'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Model:
    """Original type: model = [ ... ]
    """

    value: Union[Generic, Bank, Insurer]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'Model':
        if isinstance(x, str):
            if x == 'Generic':
                return cls(Generic())
            if x == 'Bank':
                return cls(Bank())
            if x == 'Insurer':
                return cls(Insurer())
            _atd_bad_json('Model', x)
        _atd_bad_json('Model', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'Model':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IntParameter:
    """Original type: int_parameter = { ... }
    """

    value: int
    key: str
    source: str
    as_of: str
    age_days: int

    @classmethod
    def from_json(cls, x: Any) -> 'IntParameter':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_int(x['value']) if 'value' in x else _atd_missing_json_field('IntParameter', 'value'),
                key=_atd_read_string(x['key']) if 'key' in x else _atd_missing_json_field('IntParameter', 'key'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('IntParameter', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('IntParameter', 'as_of'),
                age_days=_atd_read_int(x['age_days']) if 'age_days' in x else _atd_missing_json_field('IntParameter', 'age_days'),
            )
        else:
            _atd_bad_json('IntParameter', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_int(self.value)
        res['key'] = _atd_write_string(self.key)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['age_days'] = _atd_write_int(self.age_days)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'IntParameter':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IndustryTable:
    """Original type: beta_source = [ ... | Industry_table | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'IndustryTable'

    @staticmethod
    def to_json() -> Any:
        return 'industry_table'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class DefaultNoIndustry:
    """Original type: beta_source = [ ... | Default_no_industry | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'DefaultNoIndustry'

    @staticmethod
    def to_json() -> Any:
        return 'default_no_industry'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class BetaSource:
    """Original type: beta_source = [ ... ]
    """

    value: Union[IndustryTable, DefaultNoIndustry]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'BetaSource':
        if isinstance(x, str):
            if x == 'industry_table':
                return cls(IndustryTable())
            if x == 'default_no_industry':
                return cls(DefaultNoIndustry())
            _atd_bad_json('BetaSource', x)
        _atd_bad_json('BetaSource', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'BetaSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Inputs:
    """Original type: inputs = { ... }
    """

    fiscal_period_end: str
    country: str
    industry: Optional[str]
    price: float
    market_cap: float
    shares: float
    ebit: float
    tax_rate: float
    tax_rate_source: TaxRateSource
    statutory_tax_rate: Parameter
    depreciation_amortization: float
    capex: float
    delta_nwc: float
    fcff: float
    cash: float
    total_debt: float
    net_debt: float
    risk_free_rate: Parameter
    equity_risk_premium: Parameter
    beta: Parameter
    beta_source: BetaSource
    cost_of_equity: float
    debt_spread: Parameter
    cost_of_debt: float
    wacc: float
    growth_rate: Parameter
    terminal_growth_rate: Parameter
    projection_years: IntParameter
    enterprise_value: float
    equity_value: float

    @classmethod
    def from_json(cls, x: Any) -> 'Inputs':
        if isinstance(x, dict):
            return cls(
                fiscal_period_end=_atd_read_string(x['fiscal_period_end']) if 'fiscal_period_end' in x else _atd_missing_json_field('Inputs', 'fiscal_period_end'),
                country=_atd_read_string(x['country']) if 'country' in x else _atd_missing_json_field('Inputs', 'country'),
                industry=_atd_read_nullable(_atd_read_string)(x['industry']) if 'industry' in x else _atd_missing_json_field('Inputs', 'industry'),
                price=_atd_read_float(x['price']) if 'price' in x else _atd_missing_json_field('Inputs', 'price'),
                market_cap=_atd_read_float(x['market_cap']) if 'market_cap' in x else _atd_missing_json_field('Inputs', 'market_cap'),
                shares=_atd_read_float(x['shares']) if 'shares' in x else _atd_missing_json_field('Inputs', 'shares'),
                ebit=_atd_read_float(x['ebit']) if 'ebit' in x else _atd_missing_json_field('Inputs', 'ebit'),
                tax_rate=_atd_read_float(x['tax_rate']) if 'tax_rate' in x else _atd_missing_json_field('Inputs', 'tax_rate'),
                tax_rate_source=TaxRateSource.from_json(x['tax_rate_source']) if 'tax_rate_source' in x else _atd_missing_json_field('Inputs', 'tax_rate_source'),
                statutory_tax_rate=Parameter.from_json(x['statutory_tax_rate']) if 'statutory_tax_rate' in x else _atd_missing_json_field('Inputs', 'statutory_tax_rate'),
                depreciation_amortization=_atd_read_float(x['depreciation_amortization']) if 'depreciation_amortization' in x else _atd_missing_json_field('Inputs', 'depreciation_amortization'),
                capex=_atd_read_float(x['capex']) if 'capex' in x else _atd_missing_json_field('Inputs', 'capex'),
                delta_nwc=_atd_read_float(x['delta_nwc']) if 'delta_nwc' in x else _atd_missing_json_field('Inputs', 'delta_nwc'),
                fcff=_atd_read_float(x['fcff']) if 'fcff' in x else _atd_missing_json_field('Inputs', 'fcff'),
                cash=_atd_read_float(x['cash']) if 'cash' in x else _atd_missing_json_field('Inputs', 'cash'),
                total_debt=_atd_read_float(x['total_debt']) if 'total_debt' in x else _atd_missing_json_field('Inputs', 'total_debt'),
                net_debt=_atd_read_float(x['net_debt']) if 'net_debt' in x else _atd_missing_json_field('Inputs', 'net_debt'),
                risk_free_rate=Parameter.from_json(x['risk_free_rate']) if 'risk_free_rate' in x else _atd_missing_json_field('Inputs', 'risk_free_rate'),
                equity_risk_premium=Parameter.from_json(x['equity_risk_premium']) if 'equity_risk_premium' in x else _atd_missing_json_field('Inputs', 'equity_risk_premium'),
                beta=Parameter.from_json(x['beta']) if 'beta' in x else _atd_missing_json_field('Inputs', 'beta'),
                beta_source=BetaSource.from_json(x['beta_source']) if 'beta_source' in x else _atd_missing_json_field('Inputs', 'beta_source'),
                cost_of_equity=_atd_read_float(x['cost_of_equity']) if 'cost_of_equity' in x else _atd_missing_json_field('Inputs', 'cost_of_equity'),
                debt_spread=Parameter.from_json(x['debt_spread']) if 'debt_spread' in x else _atd_missing_json_field('Inputs', 'debt_spread'),
                cost_of_debt=_atd_read_float(x['cost_of_debt']) if 'cost_of_debt' in x else _atd_missing_json_field('Inputs', 'cost_of_debt'),
                wacc=_atd_read_float(x['wacc']) if 'wacc' in x else _atd_missing_json_field('Inputs', 'wacc'),
                growth_rate=Parameter.from_json(x['growth_rate']) if 'growth_rate' in x else _atd_missing_json_field('Inputs', 'growth_rate'),
                terminal_growth_rate=Parameter.from_json(x['terminal_growth_rate']) if 'terminal_growth_rate' in x else _atd_missing_json_field('Inputs', 'terminal_growth_rate'),
                projection_years=IntParameter.from_json(x['projection_years']) if 'projection_years' in x else _atd_missing_json_field('Inputs', 'projection_years'),
                enterprise_value=_atd_read_float(x['enterprise_value']) if 'enterprise_value' in x else _atd_missing_json_field('Inputs', 'enterprise_value'),
                equity_value=_atd_read_float(x['equity_value']) if 'equity_value' in x else _atd_missing_json_field('Inputs', 'equity_value'),
            )
        else:
            _atd_bad_json('Inputs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['fiscal_period_end'] = _atd_write_string(self.fiscal_period_end)
        res['country'] = _atd_write_string(self.country)
        res['industry'] = _atd_write_nullable(_atd_write_string)(self.industry)
        res['price'] = _atd_write_float(self.price)
        res['market_cap'] = _atd_write_float(self.market_cap)
        res['shares'] = _atd_write_float(self.shares)
        res['ebit'] = _atd_write_float(self.ebit)
        res['tax_rate'] = _atd_write_float(self.tax_rate)
        res['tax_rate_source'] = (lambda x: x.to_json())(self.tax_rate_source)
        res['statutory_tax_rate'] = (lambda x: x.to_json())(self.statutory_tax_rate)
        res['depreciation_amortization'] = _atd_write_float(self.depreciation_amortization)
        res['capex'] = _atd_write_float(self.capex)
        res['delta_nwc'] = _atd_write_float(self.delta_nwc)
        res['fcff'] = _atd_write_float(self.fcff)
        res['cash'] = _atd_write_float(self.cash)
        res['total_debt'] = _atd_write_float(self.total_debt)
        res['net_debt'] = _atd_write_float(self.net_debt)
        res['risk_free_rate'] = (lambda x: x.to_json())(self.risk_free_rate)
        res['equity_risk_premium'] = (lambda x: x.to_json())(self.equity_risk_premium)
        res['beta'] = (lambda x: x.to_json())(self.beta)
        res['beta_source'] = (lambda x: x.to_json())(self.beta_source)
        res['cost_of_equity'] = _atd_write_float(self.cost_of_equity)
        res['debt_spread'] = (lambda x: x.to_json())(self.debt_spread)
        res['cost_of_debt'] = _atd_write_float(self.cost_of_debt)
        res['wacc'] = _atd_write_float(self.wacc)
        res['growth_rate'] = (lambda x: x.to_json())(self.growth_rate)
        res['terminal_growth_rate'] = (lambda x: x.to_json())(self.terminal_growth_rate)
        res['projection_years'] = (lambda x: x.to_json())(self.projection_years)
        res['enterprise_value'] = _atd_write_float(self.enterprise_value)
        res['equity_value'] = _atd_write_float(self.equity_value)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Inputs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Classification:
    """Original type: classification = { ... }
    """

    fiscal_period_end: Optional[str]
    total_revenue: Optional[float]
    net_interest_income: Optional[float]
    nii_ratio: Optional[float]
    bank_nii_ratio_threshold: Parameter
    premiums_earned: Optional[float]
    premiums_earned_row: Optional[str]
    info_hint: Optional[Model]

    @classmethod
    def from_json(cls, x: Any) -> 'Classification':
        if isinstance(x, dict):
            return cls(
                fiscal_period_end=_atd_read_nullable(_atd_read_string)(x['fiscal_period_end']) if 'fiscal_period_end' in x else _atd_missing_json_field('Classification', 'fiscal_period_end'),
                total_revenue=_atd_read_nullable(_atd_read_float)(x['total_revenue']) if 'total_revenue' in x else _atd_missing_json_field('Classification', 'total_revenue'),
                net_interest_income=_atd_read_nullable(_atd_read_float)(x['net_interest_income']) if 'net_interest_income' in x else _atd_missing_json_field('Classification', 'net_interest_income'),
                nii_ratio=_atd_read_nullable(_atd_read_float)(x['nii_ratio']) if 'nii_ratio' in x else _atd_missing_json_field('Classification', 'nii_ratio'),
                bank_nii_ratio_threshold=Parameter.from_json(x['bank_nii_ratio_threshold']) if 'bank_nii_ratio_threshold' in x else _atd_missing_json_field('Classification', 'bank_nii_ratio_threshold'),
                premiums_earned=_atd_read_nullable(_atd_read_float)(x['premiums_earned']) if 'premiums_earned' in x else _atd_missing_json_field('Classification', 'premiums_earned'),
                premiums_earned_row=_atd_read_nullable(_atd_read_string)(x['premiums_earned_row']) if 'premiums_earned_row' in x else _atd_missing_json_field('Classification', 'premiums_earned_row'),
                info_hint=_atd_read_nullable(Model.from_json)(x['info_hint']) if 'info_hint' in x else _atd_missing_json_field('Classification', 'info_hint'),
            )
        else:
            _atd_bad_json('Classification', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['fiscal_period_end'] = _atd_write_nullable(_atd_write_string)(self.fiscal_period_end)
        res['total_revenue'] = _atd_write_nullable(_atd_write_float)(self.total_revenue)
        res['net_interest_income'] = _atd_write_nullable(_atd_write_float)(self.net_interest_income)
        res['nii_ratio'] = _atd_write_nullable(_atd_write_float)(self.nii_ratio)
        res['bank_nii_ratio_threshold'] = (lambda x: x.to_json())(self.bank_nii_ratio_threshold)
        res['premiums_earned'] = _atd_write_nullable(_atd_write_float)(self.premiums_earned)
        res['premiums_earned_row'] = _atd_write_nullable(_atd_write_string)(self.premiums_earned_row)
        res['info_hint'] = _atd_write_nullable((lambda x: x.to_json()))(self.info_hint)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Classification':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Valuation:
    """Original type: valuation = { ... }
    """

    ticker: str
    as_of: str
    valued_on: str
    currency: Optional[str]
    price: Optional[float]
    fair_value: Optional[float]
    margin_of_safety: Optional[float]
    signal: Optional[Signal]
    model: Optional[Model]
    classification: Optional[Classification]
    status: Status
    failed_reason: Optional[str]
    inputs: Optional[Inputs]

    @classmethod
    def from_json(cls, x: Any) -> 'Valuation':
        if isinstance(x, dict):
            return cls(
                ticker=_atd_read_string(x['ticker']) if 'ticker' in x else _atd_missing_json_field('Valuation', 'ticker'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Valuation', 'as_of'),
                valued_on=_atd_read_string(x['valued_on']) if 'valued_on' in x else _atd_missing_json_field('Valuation', 'valued_on'),
                currency=_atd_read_nullable(_atd_read_string)(x['currency']) if 'currency' in x else _atd_missing_json_field('Valuation', 'currency'),
                price=_atd_read_nullable(_atd_read_float)(x['price']) if 'price' in x else _atd_missing_json_field('Valuation', 'price'),
                fair_value=_atd_read_nullable(_atd_read_float)(x['fair_value']) if 'fair_value' in x else _atd_missing_json_field('Valuation', 'fair_value'),
                margin_of_safety=_atd_read_nullable(_atd_read_float)(x['margin_of_safety']) if 'margin_of_safety' in x else _atd_missing_json_field('Valuation', 'margin_of_safety'),
                signal=_atd_read_nullable(Signal.from_json)(x['signal']) if 'signal' in x else _atd_missing_json_field('Valuation', 'signal'),
                model=_atd_read_nullable(Model.from_json)(x['model']) if 'model' in x else _atd_missing_json_field('Valuation', 'model'),
                classification=_atd_read_nullable(Classification.from_json)(x['classification']) if 'classification' in x else _atd_missing_json_field('Valuation', 'classification'),
                status=Status.from_json(x['status']) if 'status' in x else _atd_missing_json_field('Valuation', 'status'),
                failed_reason=_atd_read_nullable(_atd_read_string)(x['failed_reason']) if 'failed_reason' in x else _atd_missing_json_field('Valuation', 'failed_reason'),
                inputs=_atd_read_nullable(Inputs.from_json)(x['inputs']) if 'inputs' in x else _atd_missing_json_field('Valuation', 'inputs'),
            )
        else:
            _atd_bad_json('Valuation', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['ticker'] = _atd_write_string(self.ticker)
        res['as_of'] = _atd_write_string(self.as_of)
        res['valued_on'] = _atd_write_string(self.valued_on)
        res['currency'] = _atd_write_nullable(_atd_write_string)(self.currency)
        res['price'] = _atd_write_nullable(_atd_write_float)(self.price)
        res['fair_value'] = _atd_write_nullable(_atd_write_float)(self.fair_value)
        res['margin_of_safety'] = _atd_write_nullable(_atd_write_float)(self.margin_of_safety)
        res['signal'] = _atd_write_nullable((lambda x: x.to_json()))(self.signal)
        res['model'] = _atd_write_nullable((lambda x: x.to_json()))(self.model)
        res['classification'] = _atd_write_nullable((lambda x: x.to_json()))(self.classification)
        res['status'] = (lambda x: x.to_json())(self.status)
        res['failed_reason'] = _atd_write_nullable(_atd_write_string)(self.failed_reason)
        res['inputs'] = _atd_write_nullable((lambda x: x.to_json()))(self.inputs)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Valuation':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FiscalPeriod:
    """Original type: fiscal_period = { ... }
    """

    period_end: str
    ebit: Optional[float]
    pretax_income: Optional[float]
    tax_provision: Optional[float]
    total_revenue: Optional[float]
    net_interest_income: Optional[float]
    premiums_earned: Optional[float]
    premiums_earned_row: Optional[str]
    depreciation_amortization: Optional[float]
    capex: Optional[float]
    delta_nwc: Optional[float]
    cash: Optional[float]
    total_debt: Optional[float]

    @classmethod
    def from_json(cls, x: Any) -> 'FiscalPeriod':
        if isinstance(x, dict):
            return cls(
                period_end=_atd_read_string(x['period_end']) if 'period_end' in x else _atd_missing_json_field('FiscalPeriod', 'period_end'),
                ebit=_atd_read_nullable(_atd_read_float)(x['ebit']) if 'ebit' in x else _atd_missing_json_field('FiscalPeriod', 'ebit'),
                pretax_income=_atd_read_nullable(_atd_read_float)(x['pretax_income']) if 'pretax_income' in x else _atd_missing_json_field('FiscalPeriod', 'pretax_income'),
                tax_provision=_atd_read_nullable(_atd_read_float)(x['tax_provision']) if 'tax_provision' in x else _atd_missing_json_field('FiscalPeriod', 'tax_provision'),
                total_revenue=_atd_read_nullable(_atd_read_float)(x['total_revenue']) if 'total_revenue' in x else _atd_missing_json_field('FiscalPeriod', 'total_revenue'),
                net_interest_income=_atd_read_nullable(_atd_read_float)(x['net_interest_income']) if 'net_interest_income' in x else _atd_missing_json_field('FiscalPeriod', 'net_interest_income'),
                premiums_earned=_atd_read_nullable(_atd_read_float)(x['premiums_earned']) if 'premiums_earned' in x else _atd_missing_json_field('FiscalPeriod', 'premiums_earned'),
                premiums_earned_row=_atd_read_nullable(_atd_read_string)(x['premiums_earned_row']) if 'premiums_earned_row' in x else _atd_missing_json_field('FiscalPeriod', 'premiums_earned_row'),
                depreciation_amortization=_atd_read_nullable(_atd_read_float)(x['depreciation_amortization']) if 'depreciation_amortization' in x else _atd_missing_json_field('FiscalPeriod', 'depreciation_amortization'),
                capex=_atd_read_nullable(_atd_read_float)(x['capex']) if 'capex' in x else _atd_missing_json_field('FiscalPeriod', 'capex'),
                delta_nwc=_atd_read_nullable(_atd_read_float)(x['delta_nwc']) if 'delta_nwc' in x else _atd_missing_json_field('FiscalPeriod', 'delta_nwc'),
                cash=_atd_read_nullable(_atd_read_float)(x['cash']) if 'cash' in x else _atd_missing_json_field('FiscalPeriod', 'cash'),
                total_debt=_atd_read_nullable(_atd_read_float)(x['total_debt']) if 'total_debt' in x else _atd_missing_json_field('FiscalPeriod', 'total_debt'),
            )
        else:
            _atd_bad_json('FiscalPeriod', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['period_end'] = _atd_write_string(self.period_end)
        res['ebit'] = _atd_write_nullable(_atd_write_float)(self.ebit)
        res['pretax_income'] = _atd_write_nullable(_atd_write_float)(self.pretax_income)
        res['tax_provision'] = _atd_write_nullable(_atd_write_float)(self.tax_provision)
        res['total_revenue'] = _atd_write_nullable(_atd_write_float)(self.total_revenue)
        res['net_interest_income'] = _atd_write_nullable(_atd_write_float)(self.net_interest_income)
        res['premiums_earned'] = _atd_write_nullable(_atd_write_float)(self.premiums_earned)
        res['premiums_earned_row'] = _atd_write_nullable(_atd_write_string)(self.premiums_earned_row)
        res['depreciation_amortization'] = _atd_write_nullable(_atd_write_float)(self.depreciation_amortization)
        res['capex'] = _atd_write_nullable(_atd_write_float)(self.capex)
        res['delta_nwc'] = _atd_write_nullable(_atd_write_float)(self.delta_nwc)
        res['cash'] = _atd_write_nullable(_atd_write_float)(self.cash)
        res['total_debt'] = _atd_write_nullable(_atd_write_float)(self.total_debt)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FiscalPeriod':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Financials:
    """Original type: financials = { ... }
    """

    ticker: str
    as_of: str
    currency: Optional[str]
    price: Optional[float]
    market_cap: Optional[float]
    country: Optional[str]
    industry: Optional[str]
    periods: List[FiscalPeriod]
    notes: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'Financials':
        if isinstance(x, dict):
            return cls(
                ticker=_atd_read_string(x['ticker']) if 'ticker' in x else _atd_missing_json_field('Financials', 'ticker'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Financials', 'as_of'),
                currency=_atd_read_nullable(_atd_read_string)(x['currency']) if 'currency' in x else _atd_missing_json_field('Financials', 'currency'),
                price=_atd_read_nullable(_atd_read_float)(x['price']) if 'price' in x else _atd_missing_json_field('Financials', 'price'),
                market_cap=_atd_read_nullable(_atd_read_float)(x['market_cap']) if 'market_cap' in x else _atd_missing_json_field('Financials', 'market_cap'),
                country=_atd_read_nullable(_atd_read_string)(x['country']) if 'country' in x else _atd_missing_json_field('Financials', 'country'),
                industry=_atd_read_nullable(_atd_read_string)(x['industry']) if 'industry' in x else _atd_missing_json_field('Financials', 'industry'),
                periods=_atd_read_list(FiscalPeriod.from_json)(x['periods']) if 'periods' in x else _atd_missing_json_field('Financials', 'periods'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else _atd_missing_json_field('Financials', 'notes'),
            )
        else:
            _atd_bad_json('Financials', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['ticker'] = _atd_write_string(self.ticker)
        res['as_of'] = _atd_write_string(self.as_of)
        res['currency'] = _atd_write_nullable(_atd_write_string)(self.currency)
        res['price'] = _atd_write_nullable(_atd_write_float)(self.price)
        res['market_cap'] = _atd_write_nullable(_atd_write_float)(self.market_cap)
        res['country'] = _atd_write_nullable(_atd_write_string)(self.country)
        res['industry'] = _atd_write_nullable(_atd_write_string)(self.industry)
        res['periods'] = _atd_write_list((lambda x: x.to_json()))(self.periods)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Financials':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)
