"""Generated by atdpy from type definitions in boundary.atd.

This implements classes for the types defined in 'boundary.atd', providing
methods and functions to convert data from/to JSON.
"""

# Disable flake8 entirely on this file:
# flake8: noqa

# Import annotations to allow forward references
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, NoReturn, Optional, Tuple, Union

import json

############################################################################
# Private functions
############################################################################


def _atd_missing_json_field(type_name: str, json_field_name: str) -> NoReturn:
    raise ValueError(f"missing field '{json_field_name}'"
                     f" in JSON object of type '{type_name}'")


def _atd_bad_json(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible JSON value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_bad_python(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible Python value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_read_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_json('unit', x)


def _atd_read_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_json('bool', x)


def _atd_read_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_json('int', x)


def _atd_read_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_json('float', x)


def _atd_read_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_json('str', x)


def _atd_read_list(
            read_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def read_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [read_elt(elt) for elt in elts]
        else:
            _atd_bad_json('array', elts)
    return read_list


def _atd_read_assoc_array_into_dict(
            read_key: Callable[[Any], Any],
            read_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[Any, Any]]:
    def read_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {read_key(elt[0]): read_value(elt[1]) for elt in elts}
        else:
            _atd_bad_json('array', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_dict(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def read_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_read_string(k): read_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_list(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], List[Tuple[str, Any]]]:
    def read_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(_atd_read_string(k), read_value(v))
                    for k, v in elts.items()]
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_nullable(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return read_elt(x)
    return read_nullable


def _atd_read_option(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_option(x: Any) -> Any:
        if x == 'None':
            return None
        elif isinstance(x, List) and len(x) == 2 and x[0] == 'Some':
            return read_elt(x[1])
        else:
            _atd_bad_json('option', x)
            raise AssertionError('impossible')  # keep mypy happy
    return read_option


def _atd_write_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_python('unit', x)


def _atd_write_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_python('bool', x)


def _atd_write_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_python('int', x)


def _atd_write_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_python('float', x)


def _atd_write_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_python('str', x)


def _atd_write_list(
            write_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def write_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [write_elt(elt) for elt in elts]
        else:
            _atd_bad_python('list', elts)
    return write_list


def _atd_write_assoc_dict_to_array(
            write_key: Callable[[Any], Any],
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[Any, Any]], List[Tuple[Any, Any]]]:
    def write_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(write_key(k), write_value(v)) for k, v in elts.items()]
        else:
            _atd_bad_python('Dict[str, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_dict_to_object(
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def write_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_write_string(k): write_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_python('Dict[str, <value type>]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_list_to_object(
            write_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[str, Any]]:
    def write_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {_atd_write_string(elt[0]): write_value(elt[1])
                    for elt in elts}
        else:
            _atd_bad_python('List[Tuple[<key type>, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_nullable(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return write_elt(x)
    return write_nullable


def _atd_write_option(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_option(x: Any) -> Any:
        if x is None:
            return 'None'
        else:
            return ['Some', write_elt(x)]
    return write_option


############################################################################
# Public classes
############################################################################


@dataclass
class Effective:
    """Original type: tax_rate_source = [ ... | Effective | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Effective'

    @staticmethod
    def to_json() -> Any:
        return 'Effective'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Statutory:
    """Original type: tax_rate_source = [ ... | Statutory | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Statutory'

    @staticmethod
    def to_json() -> Any:
        return 'Statutory'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class TaxRateSource:
    """Original type: tax_rate_source = [ ... ]
    """

    value: Union[Effective, Statutory]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'TaxRateSource':
        if isinstance(x, str):
            if x == 'Effective':
                return cls(Effective())
            if x == 'Statutory':
                return cls(Statutory())
            _atd_bad_json('TaxRateSource', x)
        _atd_bad_json('TaxRateSource', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'TaxRateSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Ok:
    """Original type: status = [ ... | Ok | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Ok'

    @staticmethod
    def to_json() -> Any:
        return 'Ok'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Failed:
    """Original type: status = [ ... | Failed | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Failed'

    @staticmethod
    def to_json() -> Any:
        return 'Failed'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Status:
    """Original type: status = [ ... ]
    """

    value: Union[Ok, Failed]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'Status':
        if isinstance(x, str):
            if x == 'Ok':
                return cls(Ok())
            if x == 'Failed':
                return cls(Failed())
            _atd_bad_json('Status', x)
        _atd_bad_json('Status', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'Status':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Buy:
    """Original type: signal = [ ... | Buy | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Buy'

    @staticmethod
    def to_json() -> Any:
        return 'Buy'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Hold:
    """Original type: signal = [ ... | Hold | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Hold'

    @staticmethod
    def to_json() -> Any:
        return 'Hold'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Sell:
    """Original type: signal = [ ... | Sell | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Sell'

    @staticmethod
    def to_json() -> Any:
        return 'Sell'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Signal:
    """Original type: signal = [ ... ]
    """

    value: Union[Buy, Hold, Sell]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'Signal':
        if isinstance(x, str):
            if x == 'Buy':
                return cls(Buy())
            if x == 'Hold':
                return cls(Hold())
            if x == 'Sell':
                return cls(Sell())
            _atd_bad_json('Signal', x)
        _atd_bad_json('Signal', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'Signal':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Parameter:
    """Original type: parameter = { ... }
    """

    value: float
    key: str
    source: str
    as_of: str
    age_days: int
    estimated: bool = field(default_factory=lambda: False)
    tier: str = field(default_factory=lambda: "")
    tenor_requested: str = field(default_factory=lambda: "")
    tenor_used: str = field(default_factory=lambda: "")

    @classmethod
    def from_json(cls, x: Any) -> 'Parameter':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_float(x['value']) if 'value' in x else _atd_missing_json_field('Parameter', 'value'),
                key=_atd_read_string(x['key']) if 'key' in x else _atd_missing_json_field('Parameter', 'key'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Parameter', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Parameter', 'as_of'),
                age_days=_atd_read_int(x['age_days']) if 'age_days' in x else _atd_missing_json_field('Parameter', 'age_days'),
                estimated=_atd_read_bool(x['estimated']) if 'estimated' in x else False,
                tier=_atd_read_string(x['tier']) if 'tier' in x else "",
                tenor_requested=_atd_read_string(x['tenor_requested']) if 'tenor_requested' in x else "",
                tenor_used=_atd_read_string(x['tenor_used']) if 'tenor_used' in x else "",
            )
        else:
            _atd_bad_json('Parameter', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_float(self.value)
        res['key'] = _atd_write_string(self.key)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['age_days'] = _atd_write_int(self.age_days)
        res['estimated'] = _atd_write_bool(self.estimated)
        res['tier'] = _atd_write_string(self.tier)
        res['tenor_requested'] = _atd_write_string(self.tenor_requested)
        res['tenor_used'] = _atd_write_string(self.tenor_used)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Parameter':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IntParameter:
    """Original type: int_parameter = { ... }
    """

    value: int
    key: str
    source: str
    as_of: str
    age_days: int

    @classmethod
    def from_json(cls, x: Any) -> 'IntParameter':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_int(x['value']) if 'value' in x else _atd_missing_json_field('IntParameter', 'value'),
                key=_atd_read_string(x['key']) if 'key' in x else _atd_missing_json_field('IntParameter', 'key'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('IntParameter', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('IntParameter', 'as_of'),
                age_days=_atd_read_int(x['age_days']) if 'age_days' in x else _atd_missing_json_field('IntParameter', 'age_days'),
            )
        else:
            _atd_bad_json('IntParameter', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_int(self.value)
        res['key'] = _atd_write_string(self.key)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['age_days'] = _atd_write_int(self.age_days)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'IntParameter':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IndustryTable:
    """Original type: beta_source = [ ... | Industry_table | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'IndustryTable'

    @staticmethod
    def to_json() -> Any:
        return 'industry_table'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class DefaultNoIndustry:
    """Original type: beta_source = [ ... | Default_no_industry | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'DefaultNoIndustry'

    @staticmethod
    def to_json() -> Any:
        return 'default_no_industry'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class BetaSource:
    """Original type: beta_source = [ ... ]
    """

    value: Union[IndustryTable, DefaultNoIndustry]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'BetaSource':
        if isinstance(x, str):
            if x == 'industry_table':
                return cls(IndustryTable())
            if x == 'default_no_industry':
                return cls(DefaultNoIndustry())
            _atd_bad_json('BetaSource', x)
        _atd_bad_json('BetaSource', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'BetaSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ResidualIncomeInputs:
    """Original type: residual_income_inputs = { ... }
    """

    fiscal_period_end: str
    country: str
    industry: Optional[str]
    price: float
    market_cap: float
    shares: float
    book_equity: float
    book_value_per_share: float
    net_income: float
    roe_0: float
    roe_periods: List[str]
    payout_ratio: float
    retention: float
    payout_periods: List[str]
    dividends_paid: Optional[float]
    dividends_paid_row: Optional[str]
    risk_free_rate: Parameter
    equity_risk_premium: Parameter
    beta: Parameter
    beta_source: BetaSource
    cost_of_equity: float
    mean_reversion_lambda: Parameter
    terminal_growth_rate: Parameter
    bank_terminal_roe_spread: Parameter
    projection_years: IntParameter
    roe_path: List[float]
    book_value_path: List[float]
    excess_return_path: List[float]
    pv_excess_returns: float
    terminal_value: float
    pv_terminal_value: float
    equity_value: float
    justified_price_to_book: float
    net_interest_income: Optional[float]
    provision_for_credit_losses: Optional[float]
    provision_for_credit_losses_row: Optional[str]
    provision_to_net_interest_income: Optional[float]
    net_loans: Optional[float]
    net_loans_row: Optional[str]
    provision_to_net_loans: Optional[float]

    @classmethod
    def from_json(cls, x: Any) -> 'ResidualIncomeInputs':
        if isinstance(x, dict):
            return cls(
                fiscal_period_end=_atd_read_string(x['fiscal_period_end']) if 'fiscal_period_end' in x else _atd_missing_json_field('ResidualIncomeInputs', 'fiscal_period_end'),
                country=_atd_read_string(x['country']) if 'country' in x else _atd_missing_json_field('ResidualIncomeInputs', 'country'),
                industry=_atd_read_nullable(_atd_read_string)(x['industry']) if 'industry' in x else _atd_missing_json_field('ResidualIncomeInputs', 'industry'),
                price=_atd_read_float(x['price']) if 'price' in x else _atd_missing_json_field('ResidualIncomeInputs', 'price'),
                market_cap=_atd_read_float(x['market_cap']) if 'market_cap' in x else _atd_missing_json_field('ResidualIncomeInputs', 'market_cap'),
                shares=_atd_read_float(x['shares']) if 'shares' in x else _atd_missing_json_field('ResidualIncomeInputs', 'shares'),
                book_equity=_atd_read_float(x['book_equity']) if 'book_equity' in x else _atd_missing_json_field('ResidualIncomeInputs', 'book_equity'),
                book_value_per_share=_atd_read_float(x['book_value_per_share']) if 'book_value_per_share' in x else _atd_missing_json_field('ResidualIncomeInputs', 'book_value_per_share'),
                net_income=_atd_read_float(x['net_income']) if 'net_income' in x else _atd_missing_json_field('ResidualIncomeInputs', 'net_income'),
                roe_0=_atd_read_float(x['roe_0']) if 'roe_0' in x else _atd_missing_json_field('ResidualIncomeInputs', 'roe_0'),
                roe_periods=_atd_read_list(_atd_read_string)(x['roe_periods']) if 'roe_periods' in x else _atd_missing_json_field('ResidualIncomeInputs', 'roe_periods'),
                payout_ratio=_atd_read_float(x['payout_ratio']) if 'payout_ratio' in x else _atd_missing_json_field('ResidualIncomeInputs', 'payout_ratio'),
                retention=_atd_read_float(x['retention']) if 'retention' in x else _atd_missing_json_field('ResidualIncomeInputs', 'retention'),
                payout_periods=_atd_read_list(_atd_read_string)(x['payout_periods']) if 'payout_periods' in x else _atd_missing_json_field('ResidualIncomeInputs', 'payout_periods'),
                dividends_paid=_atd_read_nullable(_atd_read_float)(x['dividends_paid']) if 'dividends_paid' in x else _atd_missing_json_field('ResidualIncomeInputs', 'dividends_paid'),
                dividends_paid_row=_atd_read_nullable(_atd_read_string)(x['dividends_paid_row']) if 'dividends_paid_row' in x else _atd_missing_json_field('ResidualIncomeInputs', 'dividends_paid_row'),
                risk_free_rate=Parameter.from_json(x['risk_free_rate']) if 'risk_free_rate' in x else _atd_missing_json_field('ResidualIncomeInputs', 'risk_free_rate'),
                equity_risk_premium=Parameter.from_json(x['equity_risk_premium']) if 'equity_risk_premium' in x else _atd_missing_json_field('ResidualIncomeInputs', 'equity_risk_premium'),
                beta=Parameter.from_json(x['beta']) if 'beta' in x else _atd_missing_json_field('ResidualIncomeInputs', 'beta'),
                beta_source=BetaSource.from_json(x['beta_source']) if 'beta_source' in x else _atd_missing_json_field('ResidualIncomeInputs', 'beta_source'),
                cost_of_equity=_atd_read_float(x['cost_of_equity']) if 'cost_of_equity' in x else _atd_missing_json_field('ResidualIncomeInputs', 'cost_of_equity'),
                mean_reversion_lambda=Parameter.from_json(x['mean_reversion_lambda']) if 'mean_reversion_lambda' in x else _atd_missing_json_field('ResidualIncomeInputs', 'mean_reversion_lambda'),
                terminal_growth_rate=Parameter.from_json(x['terminal_growth_rate']) if 'terminal_growth_rate' in x else _atd_missing_json_field('ResidualIncomeInputs', 'terminal_growth_rate'),
                bank_terminal_roe_spread=Parameter.from_json(x['bank_terminal_roe_spread']) if 'bank_terminal_roe_spread' in x else _atd_missing_json_field('ResidualIncomeInputs', 'bank_terminal_roe_spread'),
                projection_years=IntParameter.from_json(x['projection_years']) if 'projection_years' in x else _atd_missing_json_field('ResidualIncomeInputs', 'projection_years'),
                roe_path=_atd_read_list(_atd_read_float)(x['roe_path']) if 'roe_path' in x else _atd_missing_json_field('ResidualIncomeInputs', 'roe_path'),
                book_value_path=_atd_read_list(_atd_read_float)(x['book_value_path']) if 'book_value_path' in x else _atd_missing_json_field('ResidualIncomeInputs', 'book_value_path'),
                excess_return_path=_atd_read_list(_atd_read_float)(x['excess_return_path']) if 'excess_return_path' in x else _atd_missing_json_field('ResidualIncomeInputs', 'excess_return_path'),
                pv_excess_returns=_atd_read_float(x['pv_excess_returns']) if 'pv_excess_returns' in x else _atd_missing_json_field('ResidualIncomeInputs', 'pv_excess_returns'),
                terminal_value=_atd_read_float(x['terminal_value']) if 'terminal_value' in x else _atd_missing_json_field('ResidualIncomeInputs', 'terminal_value'),
                pv_terminal_value=_atd_read_float(x['pv_terminal_value']) if 'pv_terminal_value' in x else _atd_missing_json_field('ResidualIncomeInputs', 'pv_terminal_value'),
                equity_value=_atd_read_float(x['equity_value']) if 'equity_value' in x else _atd_missing_json_field('ResidualIncomeInputs', 'equity_value'),
                justified_price_to_book=_atd_read_float(x['justified_price_to_book']) if 'justified_price_to_book' in x else _atd_missing_json_field('ResidualIncomeInputs', 'justified_price_to_book'),
                net_interest_income=_atd_read_nullable(_atd_read_float)(x['net_interest_income']) if 'net_interest_income' in x else _atd_missing_json_field('ResidualIncomeInputs', 'net_interest_income'),
                provision_for_credit_losses=_atd_read_nullable(_atd_read_float)(x['provision_for_credit_losses']) if 'provision_for_credit_losses' in x else _atd_missing_json_field('ResidualIncomeInputs', 'provision_for_credit_losses'),
                provision_for_credit_losses_row=_atd_read_nullable(_atd_read_string)(x['provision_for_credit_losses_row']) if 'provision_for_credit_losses_row' in x else _atd_missing_json_field('ResidualIncomeInputs', 'provision_for_credit_losses_row'),
                provision_to_net_interest_income=_atd_read_nullable(_atd_read_float)(x['provision_to_net_interest_income']) if 'provision_to_net_interest_income' in x else _atd_missing_json_field('ResidualIncomeInputs', 'provision_to_net_interest_income'),
                net_loans=_atd_read_nullable(_atd_read_float)(x['net_loans']) if 'net_loans' in x else _atd_missing_json_field('ResidualIncomeInputs', 'net_loans'),
                net_loans_row=_atd_read_nullable(_atd_read_string)(x['net_loans_row']) if 'net_loans_row' in x else _atd_missing_json_field('ResidualIncomeInputs', 'net_loans_row'),
                provision_to_net_loans=_atd_read_nullable(_atd_read_float)(x['provision_to_net_loans']) if 'provision_to_net_loans' in x else _atd_missing_json_field('ResidualIncomeInputs', 'provision_to_net_loans'),
            )
        else:
            _atd_bad_json('ResidualIncomeInputs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['fiscal_period_end'] = _atd_write_string(self.fiscal_period_end)
        res['country'] = _atd_write_string(self.country)
        res['industry'] = _atd_write_nullable(_atd_write_string)(self.industry)
        res['price'] = _atd_write_float(self.price)
        res['market_cap'] = _atd_write_float(self.market_cap)
        res['shares'] = _atd_write_float(self.shares)
        res['book_equity'] = _atd_write_float(self.book_equity)
        res['book_value_per_share'] = _atd_write_float(self.book_value_per_share)
        res['net_income'] = _atd_write_float(self.net_income)
        res['roe_0'] = _atd_write_float(self.roe_0)
        res['roe_periods'] = _atd_write_list(_atd_write_string)(self.roe_periods)
        res['payout_ratio'] = _atd_write_float(self.payout_ratio)
        res['retention'] = _atd_write_float(self.retention)
        res['payout_periods'] = _atd_write_list(_atd_write_string)(self.payout_periods)
        res['dividends_paid'] = _atd_write_nullable(_atd_write_float)(self.dividends_paid)
        res['dividends_paid_row'] = _atd_write_nullable(_atd_write_string)(self.dividends_paid_row)
        res['risk_free_rate'] = (lambda x: x.to_json())(self.risk_free_rate)
        res['equity_risk_premium'] = (lambda x: x.to_json())(self.equity_risk_premium)
        res['beta'] = (lambda x: x.to_json())(self.beta)
        res['beta_source'] = (lambda x: x.to_json())(self.beta_source)
        res['cost_of_equity'] = _atd_write_float(self.cost_of_equity)
        res['mean_reversion_lambda'] = (lambda x: x.to_json())(self.mean_reversion_lambda)
        res['terminal_growth_rate'] = (lambda x: x.to_json())(self.terminal_growth_rate)
        res['bank_terminal_roe_spread'] = (lambda x: x.to_json())(self.bank_terminal_roe_spread)
        res['projection_years'] = (lambda x: x.to_json())(self.projection_years)
        res['roe_path'] = _atd_write_list(_atd_write_float)(self.roe_path)
        res['book_value_path'] = _atd_write_list(_atd_write_float)(self.book_value_path)
        res['excess_return_path'] = _atd_write_list(_atd_write_float)(self.excess_return_path)
        res['pv_excess_returns'] = _atd_write_float(self.pv_excess_returns)
        res['terminal_value'] = _atd_write_float(self.terminal_value)
        res['pv_terminal_value'] = _atd_write_float(self.pv_terminal_value)
        res['equity_value'] = _atd_write_float(self.equity_value)
        res['justified_price_to_book'] = _atd_write_float(self.justified_price_to_book)
        res['net_interest_income'] = _atd_write_nullable(_atd_write_float)(self.net_interest_income)
        res['provision_for_credit_losses'] = _atd_write_nullable(_atd_write_float)(self.provision_for_credit_losses)
        res['provision_for_credit_losses_row'] = _atd_write_nullable(_atd_write_string)(self.provision_for_credit_losses_row)
        res['provision_to_net_interest_income'] = _atd_write_nullable(_atd_write_float)(self.provision_to_net_interest_income)
        res['net_loans'] = _atd_write_nullable(_atd_write_float)(self.net_loans)
        res['net_loans_row'] = _atd_write_nullable(_atd_write_string)(self.net_loans_row)
        res['provision_to_net_loans'] = _atd_write_nullable(_atd_write_float)(self.provision_to_net_loans)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'ResidualIncomeInputs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Fundamental:
    """Original type: growth_source = [ ... | Fundamental | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Fundamental'

    @staticmethod
    def to_json() -> Any:
        return 'fundamental'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class HistoricalCappedAtRoic:
    """Original type: growth_source = [ ... | Historical_capped_at_roic | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'HistoricalCappedAtRoic'

    @staticmethod
    def to_json() -> Any:
        return 'historical_capped_at_roic'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Historical:
    """Original type: growth_source = [ ... | Historical | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Historical'

    @staticmethod
    def to_json() -> Any:
        return 'historical'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class GrowthSource:
    """Original type: growth_source = [ ... ]
    """

    value: Union[Fundamental, HistoricalCappedAtRoic, Historical]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'GrowthSource':
        if isinstance(x, str):
            if x == 'fundamental':
                return cls(Fundamental())
            if x == 'historical_capped_at_roic':
                return cls(HistoricalCappedAtRoic())
            if x == 'historical':
                return cls(Historical())
            _atd_bad_json('GrowthSource', x)
        _atd_bad_json('GrowthSource', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'GrowthSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Inputs:
    """Original type: inputs = { ... }
    """

    fiscal_period_end: str
    country: str
    industry: Optional[str]
    price: float
    market_cap: float
    shares: float
    ebit: float
    tax_rate: float
    tax_rate_source: TaxRateSource
    statutory_tax_rate: Parameter
    nopat: float
    depreciation_amortization: float
    depreciation_amortization_row: Optional[str]
    capex: float
    delta_nwc: float
    delta_nwc_periods: List[str]
    fcff: float
    cash: float
    total_debt: float
    total_debt_source: Optional[str]
    net_debt: float
    book_equity: float
    invested_capital: float
    roic: Optional[float]
    reinvestment: float
    reinvestment_rate: Optional[float]
    g_fundamental: Optional[float]
    g_historical: Optional[float]
    revenue_periods: List[str]
    growth_source: GrowthSource
    g0: float
    growth_clamped: bool
    growth_clamp_lower: Parameter
    growth_clamp_upper: Parameter
    mean_reversion_lambda: Parameter
    growth_path: List[float]
    risk_free_rate: Parameter
    equity_risk_premium: Parameter
    beta: Parameter
    beta_source: BetaSource
    cost_of_equity: float
    debt_spread: Parameter
    cost_of_debt: float
    wacc: float
    terminal_growth_rate: Parameter
    projection_years: IntParameter
    enterprise_value: float
    equity_value: float

    @classmethod
    def from_json(cls, x: Any) -> 'Inputs':
        if isinstance(x, dict):
            return cls(
                fiscal_period_end=_atd_read_string(x['fiscal_period_end']) if 'fiscal_period_end' in x else _atd_missing_json_field('Inputs', 'fiscal_period_end'),
                country=_atd_read_string(x['country']) if 'country' in x else _atd_missing_json_field('Inputs', 'country'),
                industry=_atd_read_nullable(_atd_read_string)(x['industry']) if 'industry' in x else _atd_missing_json_field('Inputs', 'industry'),
                price=_atd_read_float(x['price']) if 'price' in x else _atd_missing_json_field('Inputs', 'price'),
                market_cap=_atd_read_float(x['market_cap']) if 'market_cap' in x else _atd_missing_json_field('Inputs', 'market_cap'),
                shares=_atd_read_float(x['shares']) if 'shares' in x else _atd_missing_json_field('Inputs', 'shares'),
                ebit=_atd_read_float(x['ebit']) if 'ebit' in x else _atd_missing_json_field('Inputs', 'ebit'),
                tax_rate=_atd_read_float(x['tax_rate']) if 'tax_rate' in x else _atd_missing_json_field('Inputs', 'tax_rate'),
                tax_rate_source=TaxRateSource.from_json(x['tax_rate_source']) if 'tax_rate_source' in x else _atd_missing_json_field('Inputs', 'tax_rate_source'),
                statutory_tax_rate=Parameter.from_json(x['statutory_tax_rate']) if 'statutory_tax_rate' in x else _atd_missing_json_field('Inputs', 'statutory_tax_rate'),
                nopat=_atd_read_float(x['nopat']) if 'nopat' in x else _atd_missing_json_field('Inputs', 'nopat'),
                depreciation_amortization=_atd_read_float(x['depreciation_amortization']) if 'depreciation_amortization' in x else _atd_missing_json_field('Inputs', 'depreciation_amortization'),
                depreciation_amortization_row=_atd_read_nullable(_atd_read_string)(x['depreciation_amortization_row']) if 'depreciation_amortization_row' in x else _atd_missing_json_field('Inputs', 'depreciation_amortization_row'),
                capex=_atd_read_float(x['capex']) if 'capex' in x else _atd_missing_json_field('Inputs', 'capex'),
                delta_nwc=_atd_read_float(x['delta_nwc']) if 'delta_nwc' in x else _atd_missing_json_field('Inputs', 'delta_nwc'),
                delta_nwc_periods=_atd_read_list(_atd_read_string)(x['delta_nwc_periods']) if 'delta_nwc_periods' in x else _atd_missing_json_field('Inputs', 'delta_nwc_periods'),
                fcff=_atd_read_float(x['fcff']) if 'fcff' in x else _atd_missing_json_field('Inputs', 'fcff'),
                cash=_atd_read_float(x['cash']) if 'cash' in x else _atd_missing_json_field('Inputs', 'cash'),
                total_debt=_atd_read_float(x['total_debt']) if 'total_debt' in x else _atd_missing_json_field('Inputs', 'total_debt'),
                total_debt_source=_atd_read_nullable(_atd_read_string)(x['total_debt_source']) if 'total_debt_source' in x else _atd_missing_json_field('Inputs', 'total_debt_source'),
                net_debt=_atd_read_float(x['net_debt']) if 'net_debt' in x else _atd_missing_json_field('Inputs', 'net_debt'),
                book_equity=_atd_read_float(x['book_equity']) if 'book_equity' in x else _atd_missing_json_field('Inputs', 'book_equity'),
                invested_capital=_atd_read_float(x['invested_capital']) if 'invested_capital' in x else _atd_missing_json_field('Inputs', 'invested_capital'),
                roic=_atd_read_nullable(_atd_read_float)(x['roic']) if 'roic' in x else _atd_missing_json_field('Inputs', 'roic'),
                reinvestment=_atd_read_float(x['reinvestment']) if 'reinvestment' in x else _atd_missing_json_field('Inputs', 'reinvestment'),
                reinvestment_rate=_atd_read_nullable(_atd_read_float)(x['reinvestment_rate']) if 'reinvestment_rate' in x else _atd_missing_json_field('Inputs', 'reinvestment_rate'),
                g_fundamental=_atd_read_nullable(_atd_read_float)(x['g_fundamental']) if 'g_fundamental' in x else _atd_missing_json_field('Inputs', 'g_fundamental'),
                g_historical=_atd_read_nullable(_atd_read_float)(x['g_historical']) if 'g_historical' in x else _atd_missing_json_field('Inputs', 'g_historical'),
                revenue_periods=_atd_read_list(_atd_read_string)(x['revenue_periods']) if 'revenue_periods' in x else _atd_missing_json_field('Inputs', 'revenue_periods'),
                growth_source=GrowthSource.from_json(x['growth_source']) if 'growth_source' in x else _atd_missing_json_field('Inputs', 'growth_source'),
                g0=_atd_read_float(x['g0']) if 'g0' in x else _atd_missing_json_field('Inputs', 'g0'),
                growth_clamped=_atd_read_bool(x['growth_clamped']) if 'growth_clamped' in x else _atd_missing_json_field('Inputs', 'growth_clamped'),
                growth_clamp_lower=Parameter.from_json(x['growth_clamp_lower']) if 'growth_clamp_lower' in x else _atd_missing_json_field('Inputs', 'growth_clamp_lower'),
                growth_clamp_upper=Parameter.from_json(x['growth_clamp_upper']) if 'growth_clamp_upper' in x else _atd_missing_json_field('Inputs', 'growth_clamp_upper'),
                mean_reversion_lambda=Parameter.from_json(x['mean_reversion_lambda']) if 'mean_reversion_lambda' in x else _atd_missing_json_field('Inputs', 'mean_reversion_lambda'),
                growth_path=_atd_read_list(_atd_read_float)(x['growth_path']) if 'growth_path' in x else _atd_missing_json_field('Inputs', 'growth_path'),
                risk_free_rate=Parameter.from_json(x['risk_free_rate']) if 'risk_free_rate' in x else _atd_missing_json_field('Inputs', 'risk_free_rate'),
                equity_risk_premium=Parameter.from_json(x['equity_risk_premium']) if 'equity_risk_premium' in x else _atd_missing_json_field('Inputs', 'equity_risk_premium'),
                beta=Parameter.from_json(x['beta']) if 'beta' in x else _atd_missing_json_field('Inputs', 'beta'),
                beta_source=BetaSource.from_json(x['beta_source']) if 'beta_source' in x else _atd_missing_json_field('Inputs', 'beta_source'),
                cost_of_equity=_atd_read_float(x['cost_of_equity']) if 'cost_of_equity' in x else _atd_missing_json_field('Inputs', 'cost_of_equity'),
                debt_spread=Parameter.from_json(x['debt_spread']) if 'debt_spread' in x else _atd_missing_json_field('Inputs', 'debt_spread'),
                cost_of_debt=_atd_read_float(x['cost_of_debt']) if 'cost_of_debt' in x else _atd_missing_json_field('Inputs', 'cost_of_debt'),
                wacc=_atd_read_float(x['wacc']) if 'wacc' in x else _atd_missing_json_field('Inputs', 'wacc'),
                terminal_growth_rate=Parameter.from_json(x['terminal_growth_rate']) if 'terminal_growth_rate' in x else _atd_missing_json_field('Inputs', 'terminal_growth_rate'),
                projection_years=IntParameter.from_json(x['projection_years']) if 'projection_years' in x else _atd_missing_json_field('Inputs', 'projection_years'),
                enterprise_value=_atd_read_float(x['enterprise_value']) if 'enterprise_value' in x else _atd_missing_json_field('Inputs', 'enterprise_value'),
                equity_value=_atd_read_float(x['equity_value']) if 'equity_value' in x else _atd_missing_json_field('Inputs', 'equity_value'),
            )
        else:
            _atd_bad_json('Inputs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['fiscal_period_end'] = _atd_write_string(self.fiscal_period_end)
        res['country'] = _atd_write_string(self.country)
        res['industry'] = _atd_write_nullable(_atd_write_string)(self.industry)
        res['price'] = _atd_write_float(self.price)
        res['market_cap'] = _atd_write_float(self.market_cap)
        res['shares'] = _atd_write_float(self.shares)
        res['ebit'] = _atd_write_float(self.ebit)
        res['tax_rate'] = _atd_write_float(self.tax_rate)
        res['tax_rate_source'] = (lambda x: x.to_json())(self.tax_rate_source)
        res['statutory_tax_rate'] = (lambda x: x.to_json())(self.statutory_tax_rate)
        res['nopat'] = _atd_write_float(self.nopat)
        res['depreciation_amortization'] = _atd_write_float(self.depreciation_amortization)
        res['depreciation_amortization_row'] = _atd_write_nullable(_atd_write_string)(self.depreciation_amortization_row)
        res['capex'] = _atd_write_float(self.capex)
        res['delta_nwc'] = _atd_write_float(self.delta_nwc)
        res['delta_nwc_periods'] = _atd_write_list(_atd_write_string)(self.delta_nwc_periods)
        res['fcff'] = _atd_write_float(self.fcff)
        res['cash'] = _atd_write_float(self.cash)
        res['total_debt'] = _atd_write_float(self.total_debt)
        res['total_debt_source'] = _atd_write_nullable(_atd_write_string)(self.total_debt_source)
        res['net_debt'] = _atd_write_float(self.net_debt)
        res['book_equity'] = _atd_write_float(self.book_equity)
        res['invested_capital'] = _atd_write_float(self.invested_capital)
        res['roic'] = _atd_write_nullable(_atd_write_float)(self.roic)
        res['reinvestment'] = _atd_write_float(self.reinvestment)
        res['reinvestment_rate'] = _atd_write_nullable(_atd_write_float)(self.reinvestment_rate)
        res['g_fundamental'] = _atd_write_nullable(_atd_write_float)(self.g_fundamental)
        res['g_historical'] = _atd_write_nullable(_atd_write_float)(self.g_historical)
        res['revenue_periods'] = _atd_write_list(_atd_write_string)(self.revenue_periods)
        res['growth_source'] = (lambda x: x.to_json())(self.growth_source)
        res['g0'] = _atd_write_float(self.g0)
        res['growth_clamped'] = _atd_write_bool(self.growth_clamped)
        res['growth_clamp_lower'] = (lambda x: x.to_json())(self.growth_clamp_lower)
        res['growth_clamp_upper'] = (lambda x: x.to_json())(self.growth_clamp_upper)
        res['mean_reversion_lambda'] = (lambda x: x.to_json())(self.mean_reversion_lambda)
        res['growth_path'] = _atd_write_list(_atd_write_float)(self.growth_path)
        res['risk_free_rate'] = (lambda x: x.to_json())(self.risk_free_rate)
        res['equity_risk_premium'] = (lambda x: x.to_json())(self.equity_risk_premium)
        res['beta'] = (lambda x: x.to_json())(self.beta)
        res['beta_source'] = (lambda x: x.to_json())(self.beta_source)
        res['cost_of_equity'] = _atd_write_float(self.cost_of_equity)
        res['debt_spread'] = (lambda x: x.to_json())(self.debt_spread)
        res['cost_of_debt'] = _atd_write_float(self.cost_of_debt)
        res['wacc'] = _atd_write_float(self.wacc)
        res['terminal_growth_rate'] = (lambda x: x.to_json())(self.terminal_growth_rate)
        res['projection_years'] = (lambda x: x.to_json())(self.projection_years)
        res['enterprise_value'] = _atd_write_float(self.enterprise_value)
        res['equity_value'] = _atd_write_float(self.equity_value)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Inputs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Dcf:
    """Original type: model_inputs = [ ... | Dcf of ... | ... ]
    """

    value: Inputs

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Dcf'

    def to_json(self) -> Any:
        return ['dcf', (lambda x: x.to_json())(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ResidualIncome:
    """Original type: model_inputs = [ ... | Residual_income of ... | ... ]
    """

    value: ResidualIncomeInputs

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'ResidualIncome'

    def to_json(self) -> Any:
        return ['residual_income', (lambda x: x.to_json())(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ModelInputs:
    """Original type: model_inputs = [ ... ]
    """

    value: Union[Dcf, ResidualIncome]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'ModelInputs':
        if isinstance(x, List) and len(x) == 2:
            cons = x[0]
            if cons == 'dcf':
                return cls(Dcf(Inputs.from_json(x[1])))
            if cons == 'residual_income':
                return cls(ResidualIncome(ResidualIncomeInputs.from_json(x[1])))
            _atd_bad_json('ModelInputs', x)
        _atd_bad_json('ModelInputs', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'ModelInputs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Dcf_:
    """Original type: model = [ ... | Dcf | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Dcf_'

    @staticmethod
    def to_json() -> Any:
        return 'dcf'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ResidualIncome_:
    """Original type: model = [ ... | Residual_income | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'ResidualIncome_'

    @staticmethod
    def to_json() -> Any:
        return 'residual_income'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Model:
    """Original type: model = [ ... ]
    """

    value: Union[Dcf_, ResidualIncome_]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'Model':
        if isinstance(x, str):
            if x == 'dcf':
                return cls(Dcf_())
            if x == 'residual_income':
                return cls(ResidualIncome_())
            _atd_bad_json('Model', x)
        _atd_bad_json('Model', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'Model':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Floor:
    """Original type: floor = { ... }
    """

    present: Optional[bool]
    basis: str

    @classmethod
    def from_json(cls, x: Any) -> 'Floor':
        if isinstance(x, dict):
            return cls(
                present=_atd_read_nullable(_atd_read_bool)(x['present']) if 'present' in x else _atd_missing_json_field('Floor', 'present'),
                basis=_atd_read_string(x['basis']) if 'basis' in x else _atd_missing_json_field('Floor', 'basis'),
            )
        else:
            _atd_bad_json('Floor', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['present'] = _atd_write_nullable(_atd_write_bool)(self.present)
        res['basis'] = _atd_write_string(self.basis)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Floor':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class OperatingCompany:
    """Original type: entity_class = [ ... | OperatingCompany | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'OperatingCompany'

    @staticmethod
    def to_json() -> Any:
        return 'OperatingCompany'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Bank:
    """Original type: entity_class = [ ... | Bank | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Bank'

    @staticmethod
    def to_json() -> Any:
        return 'Bank'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Insurer:
    """Original type: entity_class = [ ... | Insurer | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Insurer'

    @staticmethod
    def to_json() -> Any:
        return 'Insurer'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RegulatedUtility:
    """Original type: entity_class = [ ... | RegulatedUtility | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'RegulatedUtility'

    @staticmethod
    def to_json() -> Any:
        return 'RegulatedUtility'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class MerchantPower:
    """Original type: entity_class = [ ... | MerchantPower | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'MerchantPower'

    @staticmethod
    def to_json() -> Any:
        return 'MerchantPower'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Reit:
    """Original type: entity_class = [ ... | Reit | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Reit'

    @staticmethod
    def to_json() -> Any:
        return 'Reit'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Miner:
    """Original type: entity_class = [ ... | Miner | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Miner'

    @staticmethod
    def to_json() -> Any:
        return 'Miner'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Royalty:
    """Original type: entity_class = [ ... | Royalty | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Royalty'

    @staticmethod
    def to_json() -> Any:
        return 'Royalty'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class HighGrowthSoftware:
    """Original type: entity_class = [ ... | HighGrowthSoftware | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'HighGrowthSoftware'

    @staticmethod
    def to_json() -> Any:
        return 'HighGrowthSoftware'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class PreProfit:
    """Original type: entity_class = [ ... | PreProfit | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'PreProfit'

    @staticmethod
    def to_json() -> Any:
        return 'PreProfit'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Wrapper:
    """Original type: entity_class = [ ... | Wrapper | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Wrapper'

    @staticmethod
    def to_json() -> Any:
        return 'Wrapper'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ConstructionStage:
    """Original type: entity_class = [ ... | ConstructionStage | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'ConstructionStage'

    @staticmethod
    def to_json() -> Any:
        return 'ConstructionStage'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class UnderBid:
    """Original type: entity_class = [ ... | UnderBid | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'UnderBid'

    @staticmethod
    def to_json() -> Any:
        return 'UnderBid'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Ballast:
    """Original type: entity_class = [ ... | Ballast | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Ballast'

    @staticmethod
    def to_json() -> Any:
        return 'Ballast'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class EntityClass:
    """Original type: entity_class = [ ... ]
    """

    value: Union[OperatingCompany, Bank, Insurer, RegulatedUtility, MerchantPower, Reit, Miner, Royalty, HighGrowthSoftware, PreProfit, Wrapper, ConstructionStage, UnderBid, Ballast]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'EntityClass':
        if isinstance(x, str):
            if x == 'OperatingCompany':
                return cls(OperatingCompany())
            if x == 'Bank':
                return cls(Bank())
            if x == 'Insurer':
                return cls(Insurer())
            if x == 'RegulatedUtility':
                return cls(RegulatedUtility())
            if x == 'MerchantPower':
                return cls(MerchantPower())
            if x == 'Reit':
                return cls(Reit())
            if x == 'Miner':
                return cls(Miner())
            if x == 'Royalty':
                return cls(Royalty())
            if x == 'HighGrowthSoftware':
                return cls(HighGrowthSoftware())
            if x == 'PreProfit':
                return cls(PreProfit())
            if x == 'Wrapper':
                return cls(Wrapper())
            if x == 'ConstructionStage':
                return cls(ConstructionStage())
            if x == 'UnderBid':
                return cls(UnderBid())
            if x == 'Ballast':
                return cls(Ballast())
            _atd_bad_json('EntityClass', x)
        _atd_bad_json('EntityClass', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'EntityClass':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Consistent:
    """Original type: class_check_outcome = [ ... | Consistent | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Consistent'

    @staticmethod
    def to_json() -> Any:
        return 'Consistent'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class SignatureAbsent:
    """Original type: class_check_outcome = [ ... | Signature_absent | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'SignatureAbsent'

    @staticmethod
    def to_json() -> Any:
        return 'Signature_absent'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class SignatureDiffers:
    """Original type: class_check_outcome = [ ... | Signature_differs | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'SignatureDiffers'

    @staticmethod
    def to_json() -> Any:
        return 'Signature_differs'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Disagreement:
    """Original type: class_check_outcome = [ ... | Disagreement | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Disagreement'

    @staticmethod
    def to_json() -> Any:
        return 'Disagreement'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Undeclared:
    """Original type: class_check_outcome = [ ... | Undeclared | ... ]
    """

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Undeclared'

    @staticmethod
    def to_json() -> Any:
        return 'Undeclared'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ClassCheckOutcome:
    """Original type: class_check_outcome = [ ... ]
    """

    value: Union[Consistent, SignatureAbsent, SignatureDiffers, Disagreement, Undeclared]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'ClassCheckOutcome':
        if isinstance(x, str):
            if x == 'Consistent':
                return cls(Consistent())
            if x == 'Signature_absent':
                return cls(SignatureAbsent())
            if x == 'Signature_differs':
                return cls(SignatureDiffers())
            if x == 'Disagreement':
                return cls(Disagreement())
            if x == 'Undeclared':
                return cls(Undeclared())
            _atd_bad_json('ClassCheckOutcome', x)
        _atd_bad_json('ClassCheckOutcome', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'ClassCheckOutcome':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ClassCheck:
    """Original type: class_check = { ... }
    """

    declared: Optional[EntityClass]
    indicated: Optional[EntityClass]
    outcome: ClassCheckOutcome
    fiscal_period_end: Optional[str]
    total_revenue: Optional[float]
    net_interest_income: Optional[float]
    nii_ratio: Optional[float]
    bank_nii_ratio_threshold: Parameter
    premiums_earned: Optional[float]
    premiums_earned_row: Optional[str]

    @classmethod
    def from_json(cls, x: Any) -> 'ClassCheck':
        if isinstance(x, dict):
            return cls(
                declared=_atd_read_nullable(EntityClass.from_json)(x['declared']) if 'declared' in x else _atd_missing_json_field('ClassCheck', 'declared'),
                indicated=_atd_read_nullable(EntityClass.from_json)(x['indicated']) if 'indicated' in x else _atd_missing_json_field('ClassCheck', 'indicated'),
                outcome=ClassCheckOutcome.from_json(x['outcome']) if 'outcome' in x else _atd_missing_json_field('ClassCheck', 'outcome'),
                fiscal_period_end=_atd_read_nullable(_atd_read_string)(x['fiscal_period_end']) if 'fiscal_period_end' in x else _atd_missing_json_field('ClassCheck', 'fiscal_period_end'),
                total_revenue=_atd_read_nullable(_atd_read_float)(x['total_revenue']) if 'total_revenue' in x else _atd_missing_json_field('ClassCheck', 'total_revenue'),
                net_interest_income=_atd_read_nullable(_atd_read_float)(x['net_interest_income']) if 'net_interest_income' in x else _atd_missing_json_field('ClassCheck', 'net_interest_income'),
                nii_ratio=_atd_read_nullable(_atd_read_float)(x['nii_ratio']) if 'nii_ratio' in x else _atd_missing_json_field('ClassCheck', 'nii_ratio'),
                bank_nii_ratio_threshold=Parameter.from_json(x['bank_nii_ratio_threshold']) if 'bank_nii_ratio_threshold' in x else _atd_missing_json_field('ClassCheck', 'bank_nii_ratio_threshold'),
                premiums_earned=_atd_read_nullable(_atd_read_float)(x['premiums_earned']) if 'premiums_earned' in x else _atd_missing_json_field('ClassCheck', 'premiums_earned'),
                premiums_earned_row=_atd_read_nullable(_atd_read_string)(x['premiums_earned_row']) if 'premiums_earned_row' in x else _atd_missing_json_field('ClassCheck', 'premiums_earned_row'),
            )
        else:
            _atd_bad_json('ClassCheck', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['declared'] = _atd_write_nullable((lambda x: x.to_json()))(self.declared)
        res['indicated'] = _atd_write_nullable((lambda x: x.to_json()))(self.indicated)
        res['outcome'] = (lambda x: x.to_json())(self.outcome)
        res['fiscal_period_end'] = _atd_write_nullable(_atd_write_string)(self.fiscal_period_end)
        res['total_revenue'] = _atd_write_nullable(_atd_write_float)(self.total_revenue)
        res['net_interest_income'] = _atd_write_nullable(_atd_write_float)(self.net_interest_income)
        res['nii_ratio'] = _atd_write_nullable(_atd_write_float)(self.nii_ratio)
        res['bank_nii_ratio_threshold'] = (lambda x: x.to_json())(self.bank_nii_ratio_threshold)
        res['premiums_earned'] = _atd_write_nullable(_atd_write_float)(self.premiums_earned)
        res['premiums_earned_row'] = _atd_write_nullable(_atd_write_string)(self.premiums_earned_row)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'ClassCheck':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Valuation:
    """Original type: valuation = { ... }
    """

    ticker: str
    as_of: str
    valued_on: str
    currency: Optional[str]
    price: Optional[float]
    fair_value: Optional[float]
    margin_of_safety: Optional[float]
    signal: Optional[Signal]
    entity_class: Optional[EntityClass]
    model: Optional[Model]
    class_check: Optional[ClassCheck]
    floor: Floor
    lens_note: str
    scope_limits: List[str]
    status: Status
    failed_reason: Optional[str]
    inputs: Optional[ModelInputs]

    @classmethod
    def from_json(cls, x: Any) -> 'Valuation':
        if isinstance(x, dict):
            return cls(
                ticker=_atd_read_string(x['ticker']) if 'ticker' in x else _atd_missing_json_field('Valuation', 'ticker'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Valuation', 'as_of'),
                valued_on=_atd_read_string(x['valued_on']) if 'valued_on' in x else _atd_missing_json_field('Valuation', 'valued_on'),
                currency=_atd_read_nullable(_atd_read_string)(x['currency']) if 'currency' in x else _atd_missing_json_field('Valuation', 'currency'),
                price=_atd_read_nullable(_atd_read_float)(x['price']) if 'price' in x else _atd_missing_json_field('Valuation', 'price'),
                fair_value=_atd_read_nullable(_atd_read_float)(x['fair_value']) if 'fair_value' in x else _atd_missing_json_field('Valuation', 'fair_value'),
                margin_of_safety=_atd_read_nullable(_atd_read_float)(x['margin_of_safety']) if 'margin_of_safety' in x else _atd_missing_json_field('Valuation', 'margin_of_safety'),
                signal=_atd_read_nullable(Signal.from_json)(x['signal']) if 'signal' in x else _atd_missing_json_field('Valuation', 'signal'),
                entity_class=_atd_read_nullable(EntityClass.from_json)(x['entity_class']) if 'entity_class' in x else _atd_missing_json_field('Valuation', 'entity_class'),
                model=_atd_read_nullable(Model.from_json)(x['model']) if 'model' in x else _atd_missing_json_field('Valuation', 'model'),
                class_check=_atd_read_nullable(ClassCheck.from_json)(x['class_check']) if 'class_check' in x else _atd_missing_json_field('Valuation', 'class_check'),
                floor=Floor.from_json(x['floor']) if 'floor' in x else _atd_missing_json_field('Valuation', 'floor'),
                lens_note=_atd_read_string(x['lens_note']) if 'lens_note' in x else _atd_missing_json_field('Valuation', 'lens_note'),
                scope_limits=_atd_read_list(_atd_read_string)(x['scope_limits']) if 'scope_limits' in x else _atd_missing_json_field('Valuation', 'scope_limits'),
                status=Status.from_json(x['status']) if 'status' in x else _atd_missing_json_field('Valuation', 'status'),
                failed_reason=_atd_read_nullable(_atd_read_string)(x['failed_reason']) if 'failed_reason' in x else _atd_missing_json_field('Valuation', 'failed_reason'),
                inputs=_atd_read_nullable(ModelInputs.from_json)(x['inputs']) if 'inputs' in x else _atd_missing_json_field('Valuation', 'inputs'),
            )
        else:
            _atd_bad_json('Valuation', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['ticker'] = _atd_write_string(self.ticker)
        res['as_of'] = _atd_write_string(self.as_of)
        res['valued_on'] = _atd_write_string(self.valued_on)
        res['currency'] = _atd_write_nullable(_atd_write_string)(self.currency)
        res['price'] = _atd_write_nullable(_atd_write_float)(self.price)
        res['fair_value'] = _atd_write_nullable(_atd_write_float)(self.fair_value)
        res['margin_of_safety'] = _atd_write_nullable(_atd_write_float)(self.margin_of_safety)
        res['signal'] = _atd_write_nullable((lambda x: x.to_json()))(self.signal)
        res['entity_class'] = _atd_write_nullable((lambda x: x.to_json()))(self.entity_class)
        res['model'] = _atd_write_nullable((lambda x: x.to_json()))(self.model)
        res['class_check'] = _atd_write_nullable((lambda x: x.to_json()))(self.class_check)
        res['floor'] = (lambda x: x.to_json())(self.floor)
        res['lens_note'] = _atd_write_string(self.lens_note)
        res['scope_limits'] = _atd_write_list(_atd_write_string)(self.scope_limits)
        res['status'] = (lambda x: x.to_json())(self.status)
        res['failed_reason'] = _atd_write_nullable(_atd_write_string)(self.failed_reason)
        res['inputs'] = _atd_write_nullable((lambda x: x.to_json()))(self.inputs)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Valuation':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FiscalPeriod:
    """Original type: fiscal_period = { ... }
    """

    period_end: str
    ebit: Optional[float]
    pretax_income: Optional[float]
    tax_provision: Optional[float]
    total_revenue: Optional[float]
    net_interest_income: Optional[float]
    premiums_earned: Optional[float]
    premiums_earned_row: Optional[str]
    depreciation_amortization: Optional[float]
    depreciation_amortization_row: Optional[str]
    capex: Optional[float]
    delta_nwc: Optional[float]
    cash: Optional[float]
    total_debt: Optional[float]
    total_debt_source: Optional[str]
    book_equity: Optional[float]
    net_income: Optional[float]
    dividends_paid: Optional[float]
    dividends_paid_row: Optional[str]
    provision_for_credit_losses: Optional[float]
    provision_for_credit_losses_row: Optional[str]
    net_loans: Optional[float]
    net_loans_row: Optional[str]

    @classmethod
    def from_json(cls, x: Any) -> 'FiscalPeriod':
        if isinstance(x, dict):
            return cls(
                period_end=_atd_read_string(x['period_end']) if 'period_end' in x else _atd_missing_json_field('FiscalPeriod', 'period_end'),
                ebit=_atd_read_nullable(_atd_read_float)(x['ebit']) if 'ebit' in x else _atd_missing_json_field('FiscalPeriod', 'ebit'),
                pretax_income=_atd_read_nullable(_atd_read_float)(x['pretax_income']) if 'pretax_income' in x else _atd_missing_json_field('FiscalPeriod', 'pretax_income'),
                tax_provision=_atd_read_nullable(_atd_read_float)(x['tax_provision']) if 'tax_provision' in x else _atd_missing_json_field('FiscalPeriod', 'tax_provision'),
                total_revenue=_atd_read_nullable(_atd_read_float)(x['total_revenue']) if 'total_revenue' in x else _atd_missing_json_field('FiscalPeriod', 'total_revenue'),
                net_interest_income=_atd_read_nullable(_atd_read_float)(x['net_interest_income']) if 'net_interest_income' in x else _atd_missing_json_field('FiscalPeriod', 'net_interest_income'),
                premiums_earned=_atd_read_nullable(_atd_read_float)(x['premiums_earned']) if 'premiums_earned' in x else _atd_missing_json_field('FiscalPeriod', 'premiums_earned'),
                premiums_earned_row=_atd_read_nullable(_atd_read_string)(x['premiums_earned_row']) if 'premiums_earned_row' in x else _atd_missing_json_field('FiscalPeriod', 'premiums_earned_row'),
                depreciation_amortization=_atd_read_nullable(_atd_read_float)(x['depreciation_amortization']) if 'depreciation_amortization' in x else _atd_missing_json_field('FiscalPeriod', 'depreciation_amortization'),
                depreciation_amortization_row=_atd_read_nullable(_atd_read_string)(x['depreciation_amortization_row']) if 'depreciation_amortization_row' in x else _atd_missing_json_field('FiscalPeriod', 'depreciation_amortization_row'),
                capex=_atd_read_nullable(_atd_read_float)(x['capex']) if 'capex' in x else _atd_missing_json_field('FiscalPeriod', 'capex'),
                delta_nwc=_atd_read_nullable(_atd_read_float)(x['delta_nwc']) if 'delta_nwc' in x else _atd_missing_json_field('FiscalPeriod', 'delta_nwc'),
                cash=_atd_read_nullable(_atd_read_float)(x['cash']) if 'cash' in x else _atd_missing_json_field('FiscalPeriod', 'cash'),
                total_debt=_atd_read_nullable(_atd_read_float)(x['total_debt']) if 'total_debt' in x else _atd_missing_json_field('FiscalPeriod', 'total_debt'),
                total_debt_source=_atd_read_nullable(_atd_read_string)(x['total_debt_source']) if 'total_debt_source' in x else _atd_missing_json_field('FiscalPeriod', 'total_debt_source'),
                book_equity=_atd_read_nullable(_atd_read_float)(x['book_equity']) if 'book_equity' in x else _atd_missing_json_field('FiscalPeriod', 'book_equity'),
                net_income=_atd_read_nullable(_atd_read_float)(x['net_income']) if 'net_income' in x else _atd_missing_json_field('FiscalPeriod', 'net_income'),
                dividends_paid=_atd_read_nullable(_atd_read_float)(x['dividends_paid']) if 'dividends_paid' in x else _atd_missing_json_field('FiscalPeriod', 'dividends_paid'),
                dividends_paid_row=_atd_read_nullable(_atd_read_string)(x['dividends_paid_row']) if 'dividends_paid_row' in x else _atd_missing_json_field('FiscalPeriod', 'dividends_paid_row'),
                provision_for_credit_losses=_atd_read_nullable(_atd_read_float)(x['provision_for_credit_losses']) if 'provision_for_credit_losses' in x else _atd_missing_json_field('FiscalPeriod', 'provision_for_credit_losses'),
                provision_for_credit_losses_row=_atd_read_nullable(_atd_read_string)(x['provision_for_credit_losses_row']) if 'provision_for_credit_losses_row' in x else _atd_missing_json_field('FiscalPeriod', 'provision_for_credit_losses_row'),
                net_loans=_atd_read_nullable(_atd_read_float)(x['net_loans']) if 'net_loans' in x else _atd_missing_json_field('FiscalPeriod', 'net_loans'),
                net_loans_row=_atd_read_nullable(_atd_read_string)(x['net_loans_row']) if 'net_loans_row' in x else _atd_missing_json_field('FiscalPeriod', 'net_loans_row'),
            )
        else:
            _atd_bad_json('FiscalPeriod', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['period_end'] = _atd_write_string(self.period_end)
        res['ebit'] = _atd_write_nullable(_atd_write_float)(self.ebit)
        res['pretax_income'] = _atd_write_nullable(_atd_write_float)(self.pretax_income)
        res['tax_provision'] = _atd_write_nullable(_atd_write_float)(self.tax_provision)
        res['total_revenue'] = _atd_write_nullable(_atd_write_float)(self.total_revenue)
        res['net_interest_income'] = _atd_write_nullable(_atd_write_float)(self.net_interest_income)
        res['premiums_earned'] = _atd_write_nullable(_atd_write_float)(self.premiums_earned)
        res['premiums_earned_row'] = _atd_write_nullable(_atd_write_string)(self.premiums_earned_row)
        res['depreciation_amortization'] = _atd_write_nullable(_atd_write_float)(self.depreciation_amortization)
        res['depreciation_amortization_row'] = _atd_write_nullable(_atd_write_string)(self.depreciation_amortization_row)
        res['capex'] = _atd_write_nullable(_atd_write_float)(self.capex)
        res['delta_nwc'] = _atd_write_nullable(_atd_write_float)(self.delta_nwc)
        res['cash'] = _atd_write_nullable(_atd_write_float)(self.cash)
        res['total_debt'] = _atd_write_nullable(_atd_write_float)(self.total_debt)
        res['total_debt_source'] = _atd_write_nullable(_atd_write_string)(self.total_debt_source)
        res['book_equity'] = _atd_write_nullable(_atd_write_float)(self.book_equity)
        res['net_income'] = _atd_write_nullable(_atd_write_float)(self.net_income)
        res['dividends_paid'] = _atd_write_nullable(_atd_write_float)(self.dividends_paid)
        res['dividends_paid_row'] = _atd_write_nullable(_atd_write_string)(self.dividends_paid_row)
        res['provision_for_credit_losses'] = _atd_write_nullable(_atd_write_float)(self.provision_for_credit_losses)
        res['provision_for_credit_losses_row'] = _atd_write_nullable(_atd_write_string)(self.provision_for_credit_losses_row)
        res['net_loans'] = _atd_write_nullable(_atd_write_float)(self.net_loans)
        res['net_loans_row'] = _atd_write_nullable(_atd_write_string)(self.net_loans_row)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FiscalPeriod':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Financials:
    """Original type: financials = { ... }
    """

    ticker: str
    as_of: str
    currency: Optional[str]
    price: Optional[float]
    market_cap: Optional[float]
    country: Optional[str]
    industry: Optional[str]
    periods: List[FiscalPeriod]
    notes: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'Financials':
        if isinstance(x, dict):
            return cls(
                ticker=_atd_read_string(x['ticker']) if 'ticker' in x else _atd_missing_json_field('Financials', 'ticker'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Financials', 'as_of'),
                currency=_atd_read_nullable(_atd_read_string)(x['currency']) if 'currency' in x else _atd_missing_json_field('Financials', 'currency'),
                price=_atd_read_nullable(_atd_read_float)(x['price']) if 'price' in x else _atd_missing_json_field('Financials', 'price'),
                market_cap=_atd_read_nullable(_atd_read_float)(x['market_cap']) if 'market_cap' in x else _atd_missing_json_field('Financials', 'market_cap'),
                country=_atd_read_nullable(_atd_read_string)(x['country']) if 'country' in x else _atd_missing_json_field('Financials', 'country'),
                industry=_atd_read_nullable(_atd_read_string)(x['industry']) if 'industry' in x else _atd_missing_json_field('Financials', 'industry'),
                periods=_atd_read_list(FiscalPeriod.from_json)(x['periods']) if 'periods' in x else _atd_missing_json_field('Financials', 'periods'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else _atd_missing_json_field('Financials', 'notes'),
            )
        else:
            _atd_bad_json('Financials', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['ticker'] = _atd_write_string(self.ticker)
        res['as_of'] = _atd_write_string(self.as_of)
        res['currency'] = _atd_write_nullable(_atd_write_string)(self.currency)
        res['price'] = _atd_write_nullable(_atd_write_float)(self.price)
        res['market_cap'] = _atd_write_nullable(_atd_write_float)(self.market_cap)
        res['country'] = _atd_write_nullable(_atd_write_string)(self.country)
        res['industry'] = _atd_write_nullable(_atd_write_string)(self.industry)
        res['periods'] = _atd_write_list((lambda x: x.to_json()))(self.periods)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Financials':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)
