"""Fetch tickers' fundamentals from yfinance and write boundary JSON.

    uv run python/fetch.py AAPL [MSFT ...]     ->   data/financials/<TICKER>.json

Pipeline: yfinance -> pydantic (validated vendor snapshot) -> boundary dataclasses
(generated by atdpy from schema/boundary.atd) -> JSON.

Everything yfinance-specific -- row labels, sign conventions, `.info` keys -- stays in
this file. What leaves it is `boundary.Financials`: canonical, vendor-neutral, one
currency basis, explicit None wherever the vendor supplied nothing usable. A ticker
that cannot be fetched still yields a record, with nulls and a note, so the valuation
reports Failed for it rather than silently skipping it.
"""

from __future__ import annotations

import argparse
import math
import sys
from collections.abc import Callable, Mapping
from dataclasses import fields
from datetime import date, datetime, timezone
from pathlib import Path

import pandas as pd
import yfinance as yf
from pydantic import BaseModel, ConfigDict, ValidationError, ValidationInfo, field_validator

import boundary

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "data" / "financials"


# --- pydantic: the vendor's data, validated ------------------------------------------
# yfinance output is untrusted. It is parsed into these models or it raises; the data
# rules live in the validators. Field names and signs are already canonical here.


class Quote(BaseModel):
    """Price-level fields from `.info`. Only these: fundamentals come from statements,
    which are served from a more robust endpoint and are internally consistent."""

    model_config = ConfigDict(frozen=True, strict=True)

    currency: str | None  # trading currency of price and market_cap
    financial_currency: str | None  # currency of the statements
    price: float | None
    market_cap: float | None

    @field_validator("currency", "financial_currency")
    @classmethod
    def _currency_code(cls, v: str | None) -> str | None:
        if v is not None and not (len(v) == 3 and v.isalpha()):
            raise ValueError(f"not a currency code: {v!r}")
        return v

    @field_validator("price", "market_cap")
    @classmethod
    def _finite_positive(cls, v: float | None) -> float | None:
        if v is not None and not (math.isfinite(v) and v > 0):
            raise ValueError(f"expected a finite positive number, got {v!r}")
        return v


class Profile(BaseModel):
    """Domicile and industry from `.info`, used only as lookup keys into reference/.
    Both come back empty under load, so both are nullable; blank strings are absent."""

    model_config = ConfigDict(frozen=True, strict=True)

    country: str | None
    industry: str | None

    @field_validator("country", "industry", mode="before")
    @classmethod
    def _blank_is_absent(cls, v: object) -> object:
        if isinstance(v, str):
            return v.strip() or None
        return v


NON_NEGATIVE = frozenset(
    {"total_revenue", "premiums_earned", "depreciation_amortization", "capex", "cash", "total_debt"}
)


class Statement(BaseModel):
    """One statement for one fiscal period, in the boundary's field names and signs."""

    model_config = ConfigDict(frozen=True, strict=True)

    period_end: date

    @field_validator("*", mode="before")
    @classmethod
    def _nan_is_absent(cls, v: object) -> object:
        # yfinance encodes "not reported" as NaN inside float64 frames. An infinity is
        # never a legitimate statement value.
        if isinstance(v, float):
            if math.isnan(v):
                return None
            if math.isinf(v):
                raise ValueError("infinite value")
        return v

    @field_validator("*")
    @classmethod
    def _sign_rules(cls, v: object, info: ValidationInfo) -> object:
        if info.field_name in NON_NEGATIVE and isinstance(v, float) and v < 0:
            raise ValueError(f"{info.field_name} must be >= 0, got {v}")
        return v


class IncomeStatement(Statement):
    ebit: float | None
    pretax_income: float | None
    tax_provision: float | None
    total_revenue: float | None
    net_interest_income: float | None
    premiums_earned: float | None
    premiums_earned_row: str | None  # the vendor row label that supplied premiums_earned


class CashFlowStatement(Statement):
    depreciation_amortization: float | None
    capex: float | None
    delta_nwc: float | None


class BalanceSheet(Statement):
    cash: float | None
    total_debt: float | None


# --- yfinance specifics -------------------------------------------------------------
# Vendor row label and sign per boundary field. Sign -1 converts the cash-flow
# statement's convention (outflows negative, working-capital release positive) into the
# boundary's (capex = cash spent, delta_nwc = increase in net working capital).
# Verified on yfinance 1.7.0: Operating Cash Flow minus |Capital Expenditure| reproduces
# the vendor's own Free Cash Flow row.

type RowSpec = Mapping[str, tuple[str, float]]

INCOME_ROWS: RowSpec = {
    "ebit": ("Operating Income", 1.0),
    "pretax_income": ("Pretax Income", 1.0),
    "tax_provision": ("Tax Provision", 1.0),
    "total_revenue": ("Total Revenue", 1.0),
    "net_interest_income": ("Net Interest Income", 1.0),
}
# Insurer signature: the first of these rows that carries a value. Verified absent for
# ALL, MET, PGR and ALV.DE on yfinance 1.7.0 (2026-09-18); kept so a vendor that does
# expose one is read, and the matched label is recorded for audit.
PREMIUM_ROWS = (
    "Net Premiums Earned",
    "Total Premiums Earned",
    "Premiums Earned",
    "Insurance Premiums",
    "Net Premium Earned",
)
CASHFLOW_ROWS: RowSpec = {
    "depreciation_amortization": ("Depreciation And Amortization", 1.0),
    "capex": ("Capital Expenditure", -1.0),
    "delta_nwc": ("Change In Working Capital", -1.0),
}
BALANCE_ROWS: RowSpec = {
    "cash": ("Cash Cash Equivalents And Short Term Investments", 1.0),
    "total_debt": ("Total Debt", 1.0),
}


def _columns(frame: pd.DataFrame) -> dict[date, dict[str, object]]:
    """Statement frames: one column per fiscal period end, vendor row labels as index."""
    out: dict[date, dict[str, object]] = {}
    for column, rows in frame.to_dict().items():
        if not isinstance(column, datetime):  # pd.Timestamp is a datetime
            raise TypeError(f"period column is {type(column).__name__}, not a timestamp")
        out[column.date()] = {str(label): value for label, value in rows.items()}
    return out


def _canonical_values(rows: Mapping[str, object], spec: RowSpec) -> dict[str, object]:
    out: dict[str, object] = {}
    for field, (label, sign) in spec.items():
        value = rows.get(label)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            value = float(value) * sign
        out[field] = value
    return out


def _first_present(rows: Mapping[str, object], labels: tuple[str, ...]) -> tuple[float | None, str | None]:
    for label in labels:
        value = rows.get(label)
        if isinstance(value, (int, float)) and not isinstance(value, bool) and not math.isnan(value):
            return float(value), label
    return None, None


def _income_values(rows: Mapping[str, object]) -> dict[str, object]:
    out = _canonical_values(rows, INCOME_ROWS)
    out["premiums_earned"], out["premiums_earned_row"] = _first_present(rows, PREMIUM_ROWS)
    return out


def _cashflow_values(rows: Mapping[str, object]) -> dict[str, object]:
    return _canonical_values(rows, CASHFLOW_ROWS)


def _balance_values(rows: Mapping[str, object]) -> dict[str, object]:
    return _canonical_values(rows, BALANCE_ROWS)


def _info(ticker: yf.Ticker, notes: list[str]) -> tuple[Quote | None, Profile | None]:
    """One `.info` call, validated as two independent models so a bad price does not
    lose the country, or vice versa."""
    try:
        info = ticker.info
    except Exception as e:  # the vendor call is the untrusted edge; any failure is a note
        notes.append(f"info: vendor failed: {type(e).__name__}: {e}")
        return None, None
    quote: Quote | None = None
    profile: Profile | None = None
    try:
        quote = Quote.model_validate(
            {
                "currency": info.get("currency"),
                "financial_currency": info.get("financialCurrency"),
                "price": info.get("regularMarketPrice"),
                "market_cap": info.get("marketCap"),
            }
        )
    except ValidationError as e:
        notes.append(f"quote: rejected: {e}")
    try:
        profile = Profile.model_validate({"country": info.get("country"), "industry": info.get("industry")})
    except ValidationError as e:
        notes.append(f"profile: rejected: {e}")
    return quote, profile


def _statement[S: Statement](
    ticker: yf.Ticker,
    load: Callable[[yf.Ticker], pd.DataFrame],
    name: str,
    model: type[S],
    canonical: Callable[[Mapping[str, object]], dict[str, object]],
    notes: list[str],
) -> dict[date, S]:
    """Every fiscal period of one statement that validates; the rest become notes."""
    try:
        columns = _columns(load(ticker))
    except Exception as e:
        notes.append(f"{name}: vendor failed: {type(e).__name__}: {e}")
        return {}
    out: dict[date, S] = {}
    for period_end, rows in columns.items():
        try:
            out[period_end] = model.model_validate(
                {"period_end": period_end, **canonical(rows)}
            )
        except ValidationError as e:
            notes.append(f"{name} {period_end}: rejected: {e}")
    return out


# --- canonical record ---------------------------------------------------------------


def _single_currency(quote: Quote, notes: list[str]) -> str | None:
    """One basis for price, market cap and statements, or None. Cross-currency is a
    later layer; until then a mismatch is reported, never converted or assumed."""
    if quote.currency is not None and quote.currency == quote.financial_currency:
        return quote.currency
    notes.append(
        f"no single currency basis: price currency {quote.currency!r}, "
        f"statement currency {quote.financial_currency!r}"
    )
    return None


def _period(
    end: date,
    income: IncomeStatement | None,
    cashflow: CashFlowStatement | None,
    balance: BalanceSheet | None,
) -> boundary.FiscalPeriod:
    return boundary.FiscalPeriod(
        period_end=end.isoformat(),
        ebit=income.ebit if income else None,
        pretax_income=income.pretax_income if income else None,
        tax_provision=income.tax_provision if income else None,
        total_revenue=income.total_revenue if income else None,
        net_interest_income=income.net_interest_income if income else None,
        premiums_earned=income.premiums_earned if income else None,
        premiums_earned_row=income.premiums_earned_row if income else None,
        depreciation_amortization=cashflow.depreciation_amortization if cashflow else None,
        capex=cashflow.capex if cashflow else None,
        delta_nwc=cashflow.delta_nwc if cashflow else None,
        cash=balance.cash if balance else None,
        total_debt=balance.total_debt if balance else None,
    )


def _is_empty(period: boundary.FiscalPeriod) -> bool:
    return all(getattr(period, f.name) is None for f in fields(period) if f.name != "period_end")


def fetch(symbol: str, as_of: datetime) -> boundary.Financials:
    notes: list[str] = []
    ticker = yf.Ticker(symbol)
    quote, profile = _info(ticker, notes)
    income = _statement(ticker, lambda t: t.income_stmt, "income statement", IncomeStatement, _income_values, notes)
    cashflow = _statement(ticker, lambda t: t.cashflow, "cash flow statement", CashFlowStatement, _cashflow_values, notes)
    balance = _statement(ticker, lambda t: t.balance_sheet, "balance sheet", BalanceSheet, _balance_values, notes)

    periods: list[boundary.FiscalPeriod] = []
    for end in sorted(income.keys() | cashflow.keys() | balance.keys(), reverse=True):
        period = _period(end, income.get(end), cashflow.get(end), balance.get(end))
        if _is_empty(period):
            notes.append(f"{end}: omitted, every statement field absent")
        else:
            periods.append(period)

    return boundary.Financials(
        ticker=symbol,
        as_of=as_of.isoformat(timespec="seconds"),
        currency=_single_currency(quote, notes) if quote else None,
        price=quote.price if quote else None,
        market_cap=quote.market_cap if quote else None,
        country=profile.country if profile else None,
        industry=profile.industry if profile else None,
        periods=periods,
        notes=notes,
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("tickers", nargs="+", help="symbols as the vendor spells them, e.g. AAPL BRK-B")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"output directory (default: {DEFAULT_OUT})")
    args = parser.parse_args(argv)
    tickers: list[str] = [str(t).upper() for t in args.tickers]
    out: Path = args.out
    out.mkdir(parents=True, exist_ok=True)
    as_of = datetime.now(timezone.utc)

    for symbol in tickers:
        financials = fetch(symbol, as_of)
        # allow_nan=False: a NaN that slipped through is a bug here, not invalid JSON
        # for the other side to choke on.
        text = financials.to_json_string(indent=2, allow_nan=False)
        boundary.Financials.from_json_string(text)  # parse-time type check of what we wrote
        path = out / f"{symbol}.json"
        path.write_text(text + "\n")
        summary = (
            f"{symbol}: {len(financials.periods)} period(s), currency={financials.currency}, "
            f"price={financials.price}, country={financials.country}, industry={financials.industry}"
        )
        if financials.notes:
            summary += f", {len(financials.notes)} note(s)"
        print(f"{summary} -> {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
