"""Generated by atdpy from type definitions in reference.atd.

This implements classes for the types defined in 'reference.atd', providing
methods and functions to convert data from/to JSON.
"""

# Disable flake8 entirely on this file:
# flake8: noqa

# Import annotations to allow forward references
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, NoReturn, Optional, Tuple, Union

import json

############################################################################
# Private functions
############################################################################


def _atd_missing_json_field(type_name: str, json_field_name: str) -> NoReturn:
    raise ValueError(f"missing field '{json_field_name}'"
                     f" in JSON object of type '{type_name}'")


def _atd_bad_json(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible JSON value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_bad_python(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible Python value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_read_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_json('unit', x)


def _atd_read_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_json('bool', x)


def _atd_read_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_json('int', x)


def _atd_read_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_json('float', x)


def _atd_read_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_json('str', x)


def _atd_read_list(
            read_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def read_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [read_elt(elt) for elt in elts]
        else:
            _atd_bad_json('array', elts)
    return read_list


def _atd_read_assoc_array_into_dict(
            read_key: Callable[[Any], Any],
            read_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[Any, Any]]:
    def read_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {read_key(elt[0]): read_value(elt[1]) for elt in elts}
        else:
            _atd_bad_json('array', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_dict(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def read_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_read_string(k): read_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_list(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], List[Tuple[str, Any]]]:
    def read_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(_atd_read_string(k), read_value(v))
                    for k, v in elts.items()]
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_nullable(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return read_elt(x)
    return read_nullable


def _atd_read_option(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_option(x: Any) -> Any:
        if x == 'None':
            return None
        elif isinstance(x, List) and len(x) == 2 and x[0] == 'Some':
            return read_elt(x[1])
        else:
            _atd_bad_json('option', x)
            raise AssertionError('impossible')  # keep mypy happy
    return read_option


def _atd_write_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_python('unit', x)


def _atd_write_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_python('bool', x)


def _atd_write_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_python('int', x)


def _atd_write_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_python('float', x)


def _atd_write_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_python('str', x)


def _atd_write_list(
            write_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def write_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [write_elt(elt) for elt in elts]
        else:
            _atd_bad_python('list', elts)
    return write_list


def _atd_write_assoc_dict_to_array(
            write_key: Callable[[Any], Any],
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[Any, Any]], List[Tuple[Any, Any]]]:
    def write_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(write_key(k), write_value(v)) for k, v in elts.items()]
        else:
            _atd_bad_python('Dict[str, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_dict_to_object(
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def write_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_write_string(k): write_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_python('Dict[str, <value type>]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_list_to_object(
            write_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[str, Any]]:
    def write_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {_atd_write_string(elt[0]): write_value(elt[1])
                    for elt in elts}
        else:
            _atd_bad_python('List[Tuple[<key type>, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_nullable(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return write_elt(x)
    return write_nullable


def _atd_write_option(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_option(x: Any) -> Any:
        if x is None:
            return 'None'
        else:
            return ['Some', write_elt(x)]
    return write_option


############################################################################
# Public classes
############################################################################


@dataclass
class UniverseEntry:
    """Original type: universe_entry = { ... }
    """

    ticker: str
    entity_class: str
    note: str
    expected_status: str
    lens_note: str = field(default_factory=lambda: "")
    scope_limits: List[str] = field(default_factory=lambda: [])
    expected_reason: Optional[str] = None

    @classmethod
    def from_json(cls, x: Any) -> 'UniverseEntry':
        if isinstance(x, dict):
            return cls(
                ticker=_atd_read_string(x['ticker']) if 'ticker' in x else _atd_missing_json_field('UniverseEntry', 'ticker'),
                entity_class=_atd_read_string(x['entity_class']) if 'entity_class' in x else _atd_missing_json_field('UniverseEntry', 'entity_class'),
                note=_atd_read_string(x['note']) if 'note' in x else _atd_missing_json_field('UniverseEntry', 'note'),
                expected_status=_atd_read_string(x['expected_status']) if 'expected_status' in x else _atd_missing_json_field('UniverseEntry', 'expected_status'),
                lens_note=_atd_read_string(x['lens_note']) if 'lens_note' in x else "",
                scope_limits=_atd_read_list(_atd_read_string)(x['scope_limits']) if 'scope_limits' in x else [],
                expected_reason=_atd_read_string(x['expected_reason']) if 'expected_reason' in x else None,
            )
        else:
            _atd_bad_json('UniverseEntry', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['ticker'] = _atd_write_string(self.ticker)
        res['entity_class'] = _atd_write_string(self.entity_class)
        res['note'] = _atd_write_string(self.note)
        res['expected_status'] = _atd_write_string(self.expected_status)
        res['lens_note'] = _atd_write_string(self.lens_note)
        res['scope_limits'] = _atd_write_list(_atd_write_string)(self.scope_limits)
        if self.expected_reason is not None:
            res['expected_reason'] = _atd_write_string(self.expected_reason)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'UniverseEntry':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Universe:
    """Original type: universe = { ... }
    """

    tickers: List[UniverseEntry]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Universe':
        if isinstance(x, dict):
            return cls(
                tickers=_atd_read_list(UniverseEntry.from_json)(x['tickers']) if 'tickers' in x else _atd_missing_json_field('Universe', 'tickers'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Universe', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['tickers'] = _atd_write_list((lambda x: x.to_json()))(self.tickers)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Universe':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Scalar:
    """Original type: scalar = { ... }
    """

    value: float
    source: str
    as_of: str
    max_age_days: int
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Scalar':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_float(x['value']) if 'value' in x else _atd_missing_json_field('Scalar', 'value'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Scalar', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Scalar', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('Scalar', 'max_age_days'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Scalar', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_float(self.value)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Scalar':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Curve:
    """Original type: curve = { ... }
    """

    source: str
    as_of: str
    rates: List[Tuple[str, float]]
    tier: str = field(default_factory=lambda: "")
    estimated: List[str] = field(default_factory=lambda: [])
    tenor_used: List[Tuple[str, str]] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Curve':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Curve', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Curve', 'as_of'),
                rates=_atd_read_assoc_object_into_list(_atd_read_float)(x['rates']) if 'rates' in x else _atd_missing_json_field('Curve', 'rates'),
                tier=_atd_read_string(x['tier']) if 'tier' in x else "",
                estimated=_atd_read_list(_atd_read_string)(x['estimated']) if 'estimated' in x else [],
                tenor_used=_atd_read_assoc_object_into_list(_atd_read_string)(x['tenor_used']) if 'tenor_used' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Curve', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['rates'] = _atd_write_assoc_list_to_object(_atd_write_float)(self.rates)
        res['tier'] = _atd_write_string(self.tier)
        res['estimated'] = _atd_write_list(_atd_write_string)(self.estimated)
        res['tenor_used'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.tenor_used)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Curve':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RiskFreeRates:
    """Original type: risk_free_rates = { ... }
    """

    max_age_days: int
    tenors: List[str]
    countries: List[Tuple[str, Curve]]
    aliases: List[Tuple[str, str]] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'RiskFreeRates':
        if isinstance(x, dict):
            return cls(
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('RiskFreeRates', 'max_age_days'),
                tenors=_atd_read_list(_atd_read_string)(x['tenors']) if 'tenors' in x else _atd_missing_json_field('RiskFreeRates', 'tenors'),
                countries=_atd_read_assoc_object_into_list(Curve.from_json)(x['countries']) if 'countries' in x else _atd_missing_json_field('RiskFreeRates', 'countries'),
                aliases=_atd_read_assoc_object_into_list(_atd_read_string)(x['aliases']) if 'aliases' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('RiskFreeRates', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['tenors'] = _atd_write_list(_atd_write_string)(self.tenors)
        res['countries'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.countries)
        res['aliases'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.aliases)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'RiskFreeRates':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RateSource:
    """Original type: rate_source = { ... }
    """

    tier: str
    source: str
    parser: str
    tenors: List[str]
    url: str = field(default_factory=lambda: "")
    series: List[Tuple[str, str]] = field(default_factory=lambda: [])
    substitute: List[Tuple[str, str]] = field(default_factory=lambda: [])
    proxy_of: str = field(default_factory=lambda: "")
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'RateSource':
        if isinstance(x, dict):
            return cls(
                tier=_atd_read_string(x['tier']) if 'tier' in x else _atd_missing_json_field('RateSource', 'tier'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('RateSource', 'source'),
                parser=_atd_read_string(x['parser']) if 'parser' in x else _atd_missing_json_field('RateSource', 'parser'),
                tenors=_atd_read_list(_atd_read_string)(x['tenors']) if 'tenors' in x else _atd_missing_json_field('RateSource', 'tenors'),
                url=_atd_read_string(x['url']) if 'url' in x else "",
                series=_atd_read_assoc_object_into_list(_atd_read_string)(x['series']) if 'series' in x else [],
                substitute=_atd_read_assoc_object_into_list(_atd_read_string)(x['substitute']) if 'substitute' in x else [],
                proxy_of=_atd_read_string(x['proxy_of']) if 'proxy_of' in x else "",
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('RateSource', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['tier'] = _atd_write_string(self.tier)
        res['source'] = _atd_write_string(self.source)
        res['parser'] = _atd_write_string(self.parser)
        res['tenors'] = _atd_write_list(_atd_write_string)(self.tenors)
        res['url'] = _atd_write_string(self.url)
        res['series'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.series)
        res['substitute'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.substitute)
        res['proxy_of'] = _atd_write_string(self.proxy_of)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'RateSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RateSources:
    """Original type: rate_sources = { ... }
    """

    source: str
    as_of: str
    countries: List[Tuple[str, RateSource]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'RateSources':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('RateSources', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('RateSources', 'as_of'),
                countries=_atd_read_assoc_object_into_list(RateSource.from_json)(x['countries']) if 'countries' in x else _atd_missing_json_field('RateSources', 'countries'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('RateSources', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['countries'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.countries)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'RateSources':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IntScalar:
    """Original type: int_scalar = { ... }
    """

    value: int
    source: str
    as_of: str
    max_age_days: int
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'IntScalar':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_int(x['value']) if 'value' in x else _atd_missing_json_field('IntScalar', 'value'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('IntScalar', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('IntScalar', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('IntScalar', 'max_age_days'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('IntScalar', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_int(self.value)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'IntScalar':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class CountryTable:
    """Original type: country_table = { ... }
    """

    source: str
    as_of: str
    max_age_days: int
    values: List[Tuple[str, float]]
    aliases: List[Tuple[str, str]] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'CountryTable':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('CountryTable', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('CountryTable', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('CountryTable', 'max_age_days'),
                values=_atd_read_assoc_object_into_list(_atd_read_float)(x['values']) if 'values' in x else _atd_missing_json_field('CountryTable', 'values'),
                aliases=_atd_read_assoc_object_into_list(_atd_read_string)(x['aliases']) if 'aliases' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('CountryTable', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['values'] = _atd_write_assoc_list_to_object(_atd_write_float)(self.values)
        res['aliases'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.aliases)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'CountryTable':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Params:
    """Original type: params = { ... }
    """

    projection_years: IntScalar
    debt_spread: Scalar
    bank_nii_ratio_threshold: Scalar
    growth_clamp_lower: Scalar
    growth_clamp_upper: Scalar
    mean_reversion_lambda: Scalar
    bank_terminal_roe_spread: Scalar
    insurer_terminal_roe_spread: Scalar
    mature_market_erp: Scalar
    terminal_growth_rate: CountryTable
    unwired: Any

    @classmethod
    def from_json(cls, x: Any) -> 'Params':
        if isinstance(x, dict):
            return cls(
                projection_years=IntScalar.from_json(x['projection_years']) if 'projection_years' in x else _atd_missing_json_field('Params', 'projection_years'),
                debt_spread=Scalar.from_json(x['debt_spread']) if 'debt_spread' in x else _atd_missing_json_field('Params', 'debt_spread'),
                bank_nii_ratio_threshold=Scalar.from_json(x['bank_nii_ratio_threshold']) if 'bank_nii_ratio_threshold' in x else _atd_missing_json_field('Params', 'bank_nii_ratio_threshold'),
                growth_clamp_lower=Scalar.from_json(x['growth_clamp_lower']) if 'growth_clamp_lower' in x else _atd_missing_json_field('Params', 'growth_clamp_lower'),
                growth_clamp_upper=Scalar.from_json(x['growth_clamp_upper']) if 'growth_clamp_upper' in x else _atd_missing_json_field('Params', 'growth_clamp_upper'),
                mean_reversion_lambda=Scalar.from_json(x['mean_reversion_lambda']) if 'mean_reversion_lambda' in x else _atd_missing_json_field('Params', 'mean_reversion_lambda'),
                bank_terminal_roe_spread=Scalar.from_json(x['bank_terminal_roe_spread']) if 'bank_terminal_roe_spread' in x else _atd_missing_json_field('Params', 'bank_terminal_roe_spread'),
                insurer_terminal_roe_spread=Scalar.from_json(x['insurer_terminal_roe_spread']) if 'insurer_terminal_roe_spread' in x else _atd_missing_json_field('Params', 'insurer_terminal_roe_spread'),
                mature_market_erp=Scalar.from_json(x['mature_market_erp']) if 'mature_market_erp' in x else _atd_missing_json_field('Params', 'mature_market_erp'),
                terminal_growth_rate=CountryTable.from_json(x['terminal_growth_rate']) if 'terminal_growth_rate' in x else _atd_missing_json_field('Params', 'terminal_growth_rate'),
                unwired=(lambda x: x)(x['unwired']) if 'unwired' in x else _atd_missing_json_field('Params', 'unwired'),
            )
        else:
            _atd_bad_json('Params', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['projection_years'] = (lambda x: x.to_json())(self.projection_years)
        res['debt_spread'] = (lambda x: x.to_json())(self.debt_spread)
        res['bank_nii_ratio_threshold'] = (lambda x: x.to_json())(self.bank_nii_ratio_threshold)
        res['growth_clamp_lower'] = (lambda x: x.to_json())(self.growth_clamp_lower)
        res['growth_clamp_upper'] = (lambda x: x.to_json())(self.growth_clamp_upper)
        res['mean_reversion_lambda'] = (lambda x: x.to_json())(self.mean_reversion_lambda)
        res['bank_terminal_roe_spread'] = (lambda x: x.to_json())(self.bank_terminal_roe_spread)
        res['insurer_terminal_roe_spread'] = (lambda x: x.to_json())(self.insurer_terminal_roe_spread)
        res['mature_market_erp'] = (lambda x: x.to_json())(self.mature_market_erp)
        res['terminal_growth_rate'] = (lambda x: x.to_json())(self.terminal_growth_rate)
        res['unwired'] = (lambda x: x)(self.unwired)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Params':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IndustryTable:
    """Original type: industry_table = { ... }
    """

    source: str
    as_of: str
    max_age_days: int
    values: List[Tuple[str, float]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'IndustryTable':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('IndustryTable', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('IndustryTable', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('IndustryTable', 'max_age_days'),
                values=_atd_read_assoc_object_into_list(_atd_read_float)(x['values']) if 'values' in x else _atd_missing_json_field('IndustryTable', 'values'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('IndustryTable', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['values'] = _atd_write_assoc_list_to_object(_atd_write_float)(self.values)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'IndustryTable':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxSource:
    """Original type: fx_source = { ... }
    """

    series: str
    direction: str
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FxSource':
        if isinstance(x, dict):
            return cls(
                series=_atd_read_string(x['series']) if 'series' in x else _atd_missing_json_field('FxSource', 'series'),
                direction=_atd_read_string(x['direction']) if 'direction' in x else _atd_missing_json_field('FxSource', 'direction'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FxSource', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['series'] = _atd_write_string(self.series)
        res['direction'] = _atd_write_string(self.direction)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxSources:
    """Original type: fx_sources = { ... }
    """

    source: str
    as_of: str
    max_age_days: int
    currency_countries: List[Tuple[str, str]]
    currencies: List[Tuple[str, FxSource]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FxSources':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('FxSources', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('FxSources', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('FxSources', 'max_age_days'),
                currency_countries=_atd_read_assoc_object_into_list(_atd_read_string)(x['currency_countries']) if 'currency_countries' in x else _atd_missing_json_field('FxSources', 'currency_countries'),
                currencies=_atd_read_assoc_object_into_list(FxSource.from_json)(x['currencies']) if 'currencies' in x else _atd_missing_json_field('FxSources', 'currencies'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FxSources', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['currency_countries'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.currency_countries)
        res['currencies'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.currencies)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxSources':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxRate:
    """Original type: fx_rate = { ... }
    """

    series: str
    direction: str
    as_of: str
    quoted: float
    usd_per_unit: float

    @classmethod
    def from_json(cls, x: Any) -> 'FxRate':
        if isinstance(x, dict):
            return cls(
                series=_atd_read_string(x['series']) if 'series' in x else _atd_missing_json_field('FxRate', 'series'),
                direction=_atd_read_string(x['direction']) if 'direction' in x else _atd_missing_json_field('FxRate', 'direction'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('FxRate', 'as_of'),
                quoted=_atd_read_float(x['quoted']) if 'quoted' in x else _atd_missing_json_field('FxRate', 'quoted'),
                usd_per_unit=_atd_read_float(x['usd_per_unit']) if 'usd_per_unit' in x else _atd_missing_json_field('FxRate', 'usd_per_unit'),
            )
        else:
            _atd_bad_json('FxRate', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['series'] = _atd_write_string(self.series)
        res['direction'] = _atd_write_string(self.direction)
        res['as_of'] = _atd_write_string(self.as_of)
        res['quoted'] = _atd_write_float(self.quoted)
        res['usd_per_unit'] = _atd_write_float(self.usd_per_unit)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxRate':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxRates:
    """Original type: fx_rates = { ... }
    """

    source: str
    currencies: List[Tuple[str, FxRate]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FxRates':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('FxRates', 'source'),
                currencies=_atd_read_assoc_object_into_list(FxRate.from_json)(x['currencies']) if 'currencies' in x else _atd_missing_json_field('FxRates', 'currencies'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FxRates', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['currencies'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.currencies)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxRates':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ClassRule:
    """Original type: class_rule = { ... }
    """

    lens: str
    admissible_models: List[str]
    never: str
    floor_basis_default: str
    floor_present_default: Optional[bool] = field(default_factory=lambda: None)

    @classmethod
    def from_json(cls, x: Any) -> 'ClassRule':
        if isinstance(x, dict):
            return cls(
                lens=_atd_read_string(x['lens']) if 'lens' in x else _atd_missing_json_field('ClassRule', 'lens'),
                admissible_models=_atd_read_list(_atd_read_string)(x['admissible_models']) if 'admissible_models' in x else _atd_missing_json_field('ClassRule', 'admissible_models'),
                never=_atd_read_string(x['never']) if 'never' in x else _atd_missing_json_field('ClassRule', 'never'),
                floor_basis_default=_atd_read_string(x['floor_basis_default']) if 'floor_basis_default' in x else _atd_missing_json_field('ClassRule', 'floor_basis_default'),
                floor_present_default=_atd_read_nullable(_atd_read_bool)(x['floor_present_default']) if 'floor_present_default' in x else None,
            )
        else:
            _atd_bad_json('ClassRule', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['lens'] = _atd_write_string(self.lens)
        res['admissible_models'] = _atd_write_list(_atd_write_string)(self.admissible_models)
        res['never'] = _atd_write_string(self.never)
        res['floor_basis_default'] = _atd_write_string(self.floor_basis_default)
        res['floor_present_default'] = _atd_write_nullable(_atd_write_bool)(self.floor_present_default)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'ClassRule':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Admissibility:
    """Original type: admissibility = { ... }
    """

    source: str
    as_of: str
    classes: List[Tuple[str, ClassRule]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Admissibility':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Admissibility', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Admissibility', 'as_of'),
                classes=_atd_read_assoc_object_into_list(ClassRule.from_json)(x['classes']) if 'classes' in x else _atd_missing_json_field('Admissibility', 'classes'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Admissibility', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['classes'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.classes)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Admissibility':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)
