"""Generated by atdpy from type definitions in reference.atd.

This implements classes for the types defined in 'reference.atd', providing
methods and functions to convert data from/to JSON.
"""

# Disable flake8 entirely on this file:
# flake8: noqa

# Import annotations to allow forward references
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, NoReturn, Optional, Tuple, Union

import json

############################################################################
# Private functions
############################################################################


def _atd_missing_json_field(type_name: str, json_field_name: str) -> NoReturn:
    raise ValueError(f"missing field '{json_field_name}'"
                     f" in JSON object of type '{type_name}'")


def _atd_bad_json(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible JSON value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_bad_python(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible Python value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_read_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_json('unit', x)


def _atd_read_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_json('bool', x)


def _atd_read_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_json('int', x)


def _atd_read_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_json('float', x)


def _atd_read_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_json('str', x)


def _atd_read_list(
            read_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def read_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [read_elt(elt) for elt in elts]
        else:
            _atd_bad_json('array', elts)
    return read_list


def _atd_read_assoc_array_into_dict(
            read_key: Callable[[Any], Any],
            read_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[Any, Any]]:
    def read_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {read_key(elt[0]): read_value(elt[1]) for elt in elts}
        else:
            _atd_bad_json('array', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_dict(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def read_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_read_string(k): read_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_list(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], List[Tuple[str, Any]]]:
    def read_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(_atd_read_string(k), read_value(v))
                    for k, v in elts.items()]
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_nullable(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return read_elt(x)
    return read_nullable


def _atd_read_option(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_option(x: Any) -> Any:
        if x == 'None':
            return None
        elif isinstance(x, List) and len(x) == 2 and x[0] == 'Some':
            return read_elt(x[1])
        else:
            _atd_bad_json('option', x)
            raise AssertionError('impossible')  # keep mypy happy
    return read_option


def _atd_write_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_python('unit', x)


def _atd_write_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_python('bool', x)


def _atd_write_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_python('int', x)


def _atd_write_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_python('float', x)


def _atd_write_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_python('str', x)


def _atd_write_list(
            write_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def write_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [write_elt(elt) for elt in elts]
        else:
            _atd_bad_python('list', elts)
    return write_list


def _atd_write_assoc_dict_to_array(
            write_key: Callable[[Any], Any],
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[Any, Any]], List[Tuple[Any, Any]]]:
    def write_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(write_key(k), write_value(v)) for k, v in elts.items()]
        else:
            _atd_bad_python('Dict[str, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_dict_to_object(
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def write_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_write_string(k): write_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_python('Dict[str, <value type>]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_list_to_object(
            write_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[str, Any]]:
    def write_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {_atd_write_string(elt[0]): write_value(elt[1])
                    for elt in elts}
        else:
            _atd_bad_python('List[Tuple[<key type>, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_nullable(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return write_elt(x)
    return write_nullable


def _atd_write_option(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_option(x: Any) -> Any:
        if x is None:
            return 'None'
        else:
            return ['Some', write_elt(x)]
    return write_option


############################################################################
# Public classes
############################################################################


@dataclass
class XbrlField:
    """Original type: xbrl_field = { ... }
    """

    kind: str
    tags: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'XbrlField':
        if isinstance(x, dict):
            return cls(
                kind=_atd_read_string(x['kind']) if 'kind' in x else _atd_missing_json_field('XbrlField', 'kind'),
                tags=_atd_read_list(_atd_read_string)(x['tags']) if 'tags' in x else _atd_missing_json_field('XbrlField', 'tags'),
            )
        else:
            _atd_bad_json('XbrlField', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['kind'] = _atd_write_string(self.kind)
        res['tags'] = _atd_write_list(_atd_write_string)(self.tags)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'XbrlField':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class NiiRecipe:
    """Original type: nii_recipe = { ... }
    """

    interest_revenue: List[str]
    interest_expense: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'NiiRecipe':
        if isinstance(x, dict):
            return cls(
                interest_revenue=_atd_read_list(_atd_read_string)(x['interest_revenue']) if 'interest_revenue' in x else _atd_missing_json_field('NiiRecipe', 'interest_revenue'),
                interest_expense=_atd_read_list(_atd_read_string)(x['interest_expense']) if 'interest_expense' in x else _atd_missing_json_field('NiiRecipe', 'interest_expense'),
            )
        else:
            _atd_bad_json('NiiRecipe', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['interest_revenue'] = _atd_write_list(_atd_write_string)(self.interest_revenue)
        res['interest_expense'] = _atd_write_list(_atd_write_string)(self.interest_expense)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'NiiRecipe':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class XbrlTags:
    """Original type: xbrl_tags = { ... }
    """

    source: str
    as_of: str
    cross_check_threshold: float
    max_filing_age_days: int
    annual_forms: List[str]
    annual_span_days: List[int]
    fields: List[Tuple[str, XbrlField]]
    ifrs_full_fields: List[Tuple[str, XbrlField]]
    ifrs_full_net_interest_income: NiiRecipe
    depreciation_components: List[str]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'XbrlTags':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('XbrlTags', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('XbrlTags', 'as_of'),
                cross_check_threshold=_atd_read_float(x['cross_check_threshold']) if 'cross_check_threshold' in x else _atd_missing_json_field('XbrlTags', 'cross_check_threshold'),
                max_filing_age_days=_atd_read_int(x['max_filing_age_days']) if 'max_filing_age_days' in x else _atd_missing_json_field('XbrlTags', 'max_filing_age_days'),
                annual_forms=_atd_read_list(_atd_read_string)(x['annual_forms']) if 'annual_forms' in x else _atd_missing_json_field('XbrlTags', 'annual_forms'),
                annual_span_days=_atd_read_list(_atd_read_int)(x['annual_span_days']) if 'annual_span_days' in x else _atd_missing_json_field('XbrlTags', 'annual_span_days'),
                fields=_atd_read_assoc_object_into_list(XbrlField.from_json)(x['fields']) if 'fields' in x else _atd_missing_json_field('XbrlTags', 'fields'),
                ifrs_full_fields=_atd_read_assoc_object_into_list(XbrlField.from_json)(x['ifrs_full_fields']) if 'ifrs_full_fields' in x else _atd_missing_json_field('XbrlTags', 'ifrs_full_fields'),
                ifrs_full_net_interest_income=NiiRecipe.from_json(x['ifrs_full_net_interest_income']) if 'ifrs_full_net_interest_income' in x else _atd_missing_json_field('XbrlTags', 'ifrs_full_net_interest_income'),
                depreciation_components=_atd_read_list(_atd_read_string)(x['depreciation_components']) if 'depreciation_components' in x else _atd_missing_json_field('XbrlTags', 'depreciation_components'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('XbrlTags', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['cross_check_threshold'] = _atd_write_float(self.cross_check_threshold)
        res['max_filing_age_days'] = _atd_write_int(self.max_filing_age_days)
        res['annual_forms'] = _atd_write_list(_atd_write_string)(self.annual_forms)
        res['annual_span_days'] = _atd_write_list(_atd_write_int)(self.annual_span_days)
        res['fields'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.fields)
        res['ifrs_full_fields'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.ifrs_full_fields)
        res['ifrs_full_net_interest_income'] = (lambda x: x.to_json())(self.ifrs_full_net_interest_income)
        res['depreciation_components'] = _atd_write_list(_atd_write_string)(self.depreciation_components)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'XbrlTags':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class UniverseEntry:
    """Original type: universe_entry = { ... }
    """

    ticker: str
    entity_class: str
    why: str
    scope_limits: List[str] = field(default_factory=lambda: [])
    cik: Optional[str] = None

    @classmethod
    def from_json(cls, x: Any) -> 'UniverseEntry':
        if isinstance(x, dict):
            return cls(
                ticker=_atd_read_string(x['ticker']) if 'ticker' in x else _atd_missing_json_field('UniverseEntry', 'ticker'),
                entity_class=_atd_read_string(x['entity_class']) if 'entity_class' in x else _atd_missing_json_field('UniverseEntry', 'entity_class'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('UniverseEntry', 'why'),
                scope_limits=_atd_read_list(_atd_read_string)(x['scope_limits']) if 'scope_limits' in x else [],
                cik=_atd_read_string(x['cik']) if 'cik' in x else None,
            )
        else:
            _atd_bad_json('UniverseEntry', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['ticker'] = _atd_write_string(self.ticker)
        res['entity_class'] = _atd_write_string(self.entity_class)
        res['why'] = _atd_write_string(self.why)
        res['scope_limits'] = _atd_write_list(_atd_write_string)(self.scope_limits)
        if self.cik is not None:
            res['cik'] = _atd_write_string(self.cik)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'UniverseEntry':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Universe:
    """Original type: universe = { ... }
    """

    tickers: List[UniverseEntry]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Universe':
        if isinstance(x, dict):
            return cls(
                tickers=_atd_read_list(UniverseEntry.from_json)(x['tickers']) if 'tickers' in x else _atd_missing_json_field('Universe', 'tickers'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Universe', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['tickers'] = _atd_write_list((lambda x: x.to_json()))(self.tickers)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Universe':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class PointCountSources:
    """Original type: point_count_sources = { ... }
    """

    cover_page: List[str]
    balance_sheet: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'PointCountSources':
        if isinstance(x, dict):
            return cls(
                cover_page=_atd_read_list(_atd_read_string)(x['cover_page']) if 'cover_page' in x else _atd_missing_json_field('PointCountSources', 'cover_page'),
                balance_sheet=_atd_read_list(_atd_read_string)(x['balance_sheet']) if 'balance_sheet' in x else _atd_missing_json_field('PointCountSources', 'balance_sheet'),
            )
        else:
            _atd_bad_json('PointCountSources', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['cover_page'] = _atd_write_list(_atd_write_string)(self.cover_page)
        res['balance_sheet'] = _atd_write_list(_atd_write_string)(self.balance_sheet)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'PointCountSources':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class SharesForMarketCap:
    """Original type: shares_for_market_cap = { ... }
    """

    name: str
    why: str
    live: str
    point_in_time: PointCountSources
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'SharesForMarketCap':
        if isinstance(x, dict):
            return cls(
                name=_atd_read_string(x['name']) if 'name' in x else _atd_missing_json_field('SharesForMarketCap', 'name'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('SharesForMarketCap', 'why'),
                live=_atd_read_string(x['live']) if 'live' in x else _atd_missing_json_field('SharesForMarketCap', 'live'),
                point_in_time=PointCountSources.from_json(x['point_in_time']) if 'point_in_time' in x else _atd_missing_json_field('SharesForMarketCap', 'point_in_time'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('SharesForMarketCap', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['name'] = _atd_write_string(self.name)
        res['why'] = _atd_write_string(self.why)
        res['live'] = _atd_write_string(self.live)
        res['point_in_time'] = (lambda x: x.to_json())(self.point_in_time)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'SharesForMarketCap':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class SharesForFlows:
    """Original type: shares_for_flows = { ... }
    """

    name: str
    why: str
    xbrl: List[str]
    ifrs: List[str]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'SharesForFlows':
        if isinstance(x, dict):
            return cls(
                name=_atd_read_string(x['name']) if 'name' in x else _atd_missing_json_field('SharesForFlows', 'name'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('SharesForFlows', 'why'),
                xbrl=_atd_read_list(_atd_read_string)(x['xbrl']) if 'xbrl' in x else _atd_missing_json_field('SharesForFlows', 'xbrl'),
                ifrs=_atd_read_list(_atd_read_string)(x['ifrs']) if 'ifrs' in x else _atd_missing_json_field('SharesForFlows', 'ifrs'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('SharesForFlows', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['name'] = _atd_write_string(self.name)
        res['why'] = _atd_write_string(self.why)
        res['xbrl'] = _atd_write_list(_atd_write_string)(self.xbrl)
        res['ifrs'] = _atd_write_list(_atd_write_string)(self.ifrs)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'SharesForFlows':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class SensitivitySteps:
    """Original type: sensitivity_steps = { ... }
    """

    growth: float
    lambda_: float
    terminal_growth: float
    discount_rate: float
    base_fraction: float
    source: str
    as_of: str
    max_age_days: int
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'SensitivitySteps':
        if isinstance(x, dict):
            return cls(
                growth=_atd_read_float(x['growth']) if 'growth' in x else _atd_missing_json_field('SensitivitySteps', 'growth'),
                lambda_=_atd_read_float(x['lambda']) if 'lambda' in x else _atd_missing_json_field('SensitivitySteps', 'lambda'),
                terminal_growth=_atd_read_float(x['terminal_growth']) if 'terminal_growth' in x else _atd_missing_json_field('SensitivitySteps', 'terminal_growth'),
                discount_rate=_atd_read_float(x['discount_rate']) if 'discount_rate' in x else _atd_missing_json_field('SensitivitySteps', 'discount_rate'),
                base_fraction=_atd_read_float(x['base_fraction']) if 'base_fraction' in x else _atd_missing_json_field('SensitivitySteps', 'base_fraction'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('SensitivitySteps', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('SensitivitySteps', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('SensitivitySteps', 'max_age_days'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('SensitivitySteps', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['growth'] = _atd_write_float(self.growth)
        res['lambda'] = _atd_write_float(self.lambda_)
        res['terminal_growth'] = _atd_write_float(self.terminal_growth)
        res['discount_rate'] = _atd_write_float(self.discount_rate)
        res['base_fraction'] = _atd_write_float(self.base_fraction)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'SensitivitySteps':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Scalar:
    """Original type: scalar = { ... }
    """

    value: float
    source: str
    as_of: str
    max_age_days: int
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Scalar':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_float(x['value']) if 'value' in x else _atd_missing_json_field('Scalar', 'value'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Scalar', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Scalar', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('Scalar', 'max_age_days'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Scalar', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_float(self.value)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Scalar':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Curve:
    """Original type: curve = { ... }
    """

    source: str
    as_of: str
    rates: List[Tuple[str, float]]
    tier: str = field(default_factory=lambda: "")
    estimated: List[str] = field(default_factory=lambda: [])
    tenor_used: List[Tuple[str, str]] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Curve':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Curve', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Curve', 'as_of'),
                rates=_atd_read_assoc_object_into_list(_atd_read_float)(x['rates']) if 'rates' in x else _atd_missing_json_field('Curve', 'rates'),
                tier=_atd_read_string(x['tier']) if 'tier' in x else "",
                estimated=_atd_read_list(_atd_read_string)(x['estimated']) if 'estimated' in x else [],
                tenor_used=_atd_read_assoc_object_into_list(_atd_read_string)(x['tenor_used']) if 'tenor_used' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Curve', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['rates'] = _atd_write_assoc_list_to_object(_atd_write_float)(self.rates)
        res['tier'] = _atd_write_string(self.tier)
        res['estimated'] = _atd_write_list(_atd_write_string)(self.estimated)
        res['tenor_used'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.tenor_used)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Curve':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RiskFreeRates:
    """Original type: risk_free_rates = { ... }
    """

    max_age_days: int
    tenors: List[str]
    countries: List[Tuple[str, Curve]]
    aliases: List[Tuple[str, str]] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'RiskFreeRates':
        if isinstance(x, dict):
            return cls(
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('RiskFreeRates', 'max_age_days'),
                tenors=_atd_read_list(_atd_read_string)(x['tenors']) if 'tenors' in x else _atd_missing_json_field('RiskFreeRates', 'tenors'),
                countries=_atd_read_assoc_object_into_list(Curve.from_json)(x['countries']) if 'countries' in x else _atd_missing_json_field('RiskFreeRates', 'countries'),
                aliases=_atd_read_assoc_object_into_list(_atd_read_string)(x['aliases']) if 'aliases' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('RiskFreeRates', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['tenors'] = _atd_write_list(_atd_write_string)(self.tenors)
        res['countries'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.countries)
        res['aliases'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.aliases)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'RiskFreeRates':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RefinementPolicy:
    """Original type: refinement_policy = { ... }
    """

    max_refinements_per_field: int
    on_miss: str

    @classmethod
    def from_json(cls, x: Any) -> 'RefinementPolicy':
        if isinstance(x, dict):
            return cls(
                max_refinements_per_field=_atd_read_int(x['max_refinements_per_field']) if 'max_refinements_per_field' in x else _atd_missing_json_field('RefinementPolicy', 'max_refinements_per_field'),
                on_miss=_atd_read_string(x['on_miss']) if 'on_miss' in x else _atd_missing_json_field('RefinementPolicy', 'on_miss'),
            )
        else:
            _atd_bad_json('RefinementPolicy', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['max_refinements_per_field'] = _atd_write_int(self.max_refinements_per_field)
        res['on_miss'] = _atd_write_string(self.on_miss)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'RefinementPolicy':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RateSource:
    """Original type: rate_source = { ... }
    """

    tier: str
    source: str
    parser: str
    tenors: List[str]
    url: str = field(default_factory=lambda: "")
    series: List[Tuple[str, str]] = field(default_factory=lambda: [])
    substitute: List[Tuple[str, str]] = field(default_factory=lambda: [])
    proxy_of: str = field(default_factory=lambda: "")
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'RateSource':
        if isinstance(x, dict):
            return cls(
                tier=_atd_read_string(x['tier']) if 'tier' in x else _atd_missing_json_field('RateSource', 'tier'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('RateSource', 'source'),
                parser=_atd_read_string(x['parser']) if 'parser' in x else _atd_missing_json_field('RateSource', 'parser'),
                tenors=_atd_read_list(_atd_read_string)(x['tenors']) if 'tenors' in x else _atd_missing_json_field('RateSource', 'tenors'),
                url=_atd_read_string(x['url']) if 'url' in x else "",
                series=_atd_read_assoc_object_into_list(_atd_read_string)(x['series']) if 'series' in x else [],
                substitute=_atd_read_assoc_object_into_list(_atd_read_string)(x['substitute']) if 'substitute' in x else [],
                proxy_of=_atd_read_string(x['proxy_of']) if 'proxy_of' in x else "",
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('RateSource', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['tier'] = _atd_write_string(self.tier)
        res['source'] = _atd_write_string(self.source)
        res['parser'] = _atd_write_string(self.parser)
        res['tenors'] = _atd_write_list(_atd_write_string)(self.tenors)
        res['url'] = _atd_write_string(self.url)
        res['series'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.series)
        res['substitute'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.substitute)
        res['proxy_of'] = _atd_write_string(self.proxy_of)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'RateSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class RateSources:
    """Original type: rate_sources = { ... }
    """

    source: str
    as_of: str
    countries: List[Tuple[str, RateSource]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'RateSources':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('RateSources', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('RateSources', 'as_of'),
                countries=_atd_read_assoc_object_into_list(RateSource.from_json)(x['countries']) if 'countries' in x else _atd_missing_json_field('RateSources', 'countries'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('RateSources', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['countries'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.countries)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'RateSources':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IntScalar:
    """Original type: int_scalar = { ... }
    """

    value: int
    source: str
    as_of: str
    max_age_days: int
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'IntScalar':
        if isinstance(x, dict):
            return cls(
                value=_atd_read_int(x['value']) if 'value' in x else _atd_missing_json_field('IntScalar', 'value'),
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('IntScalar', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('IntScalar', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('IntScalar', 'max_age_days'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('IntScalar', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['value'] = _atd_write_int(self.value)
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'IntScalar':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class CountryTable:
    """Original type: country_table = { ... }
    """

    source: str
    as_of: str
    max_age_days: int
    values: List[Tuple[str, float]]
    aliases: List[Tuple[str, str]] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'CountryTable':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('CountryTable', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('CountryTable', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('CountryTable', 'max_age_days'),
                values=_atd_read_assoc_object_into_list(_atd_read_float)(x['values']) if 'values' in x else _atd_missing_json_field('CountryTable', 'values'),
                aliases=_atd_read_assoc_object_into_list(_atd_read_string)(x['aliases']) if 'aliases' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('CountryTable', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['values'] = _atd_write_assoc_list_to_object(_atd_write_float)(self.values)
        res['aliases'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.aliases)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'CountryTable':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Params:
    """Original type: params = { ... }
    """

    projection_years: IntScalar
    debt_spread: Scalar
    bank_nii_ratio_threshold: Scalar
    growth_clamp_lower: Scalar
    growth_clamp_upper: Scalar
    mean_reversion_lambda: Scalar
    mature_market_erp: Scalar
    midcycle_window_years: IntScalar
    sensitivity_steps: SensitivitySteps
    terminal_growth_rate: CountryTable
    unwired: Any

    @classmethod
    def from_json(cls, x: Any) -> 'Params':
        if isinstance(x, dict):
            return cls(
                projection_years=IntScalar.from_json(x['projection_years']) if 'projection_years' in x else _atd_missing_json_field('Params', 'projection_years'),
                debt_spread=Scalar.from_json(x['debt_spread']) if 'debt_spread' in x else _atd_missing_json_field('Params', 'debt_spread'),
                bank_nii_ratio_threshold=Scalar.from_json(x['bank_nii_ratio_threshold']) if 'bank_nii_ratio_threshold' in x else _atd_missing_json_field('Params', 'bank_nii_ratio_threshold'),
                growth_clamp_lower=Scalar.from_json(x['growth_clamp_lower']) if 'growth_clamp_lower' in x else _atd_missing_json_field('Params', 'growth_clamp_lower'),
                growth_clamp_upper=Scalar.from_json(x['growth_clamp_upper']) if 'growth_clamp_upper' in x else _atd_missing_json_field('Params', 'growth_clamp_upper'),
                mean_reversion_lambda=Scalar.from_json(x['mean_reversion_lambda']) if 'mean_reversion_lambda' in x else _atd_missing_json_field('Params', 'mean_reversion_lambda'),
                mature_market_erp=Scalar.from_json(x['mature_market_erp']) if 'mature_market_erp' in x else _atd_missing_json_field('Params', 'mature_market_erp'),
                midcycle_window_years=IntScalar.from_json(x['midcycle_window_years']) if 'midcycle_window_years' in x else _atd_missing_json_field('Params', 'midcycle_window_years'),
                sensitivity_steps=SensitivitySteps.from_json(x['sensitivity_steps']) if 'sensitivity_steps' in x else _atd_missing_json_field('Params', 'sensitivity_steps'),
                terminal_growth_rate=CountryTable.from_json(x['terminal_growth_rate']) if 'terminal_growth_rate' in x else _atd_missing_json_field('Params', 'terminal_growth_rate'),
                unwired=(lambda x: x)(x['unwired']) if 'unwired' in x else _atd_missing_json_field('Params', 'unwired'),
            )
        else:
            _atd_bad_json('Params', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['projection_years'] = (lambda x: x.to_json())(self.projection_years)
        res['debt_spread'] = (lambda x: x.to_json())(self.debt_spread)
        res['bank_nii_ratio_threshold'] = (lambda x: x.to_json())(self.bank_nii_ratio_threshold)
        res['growth_clamp_lower'] = (lambda x: x.to_json())(self.growth_clamp_lower)
        res['growth_clamp_upper'] = (lambda x: x.to_json())(self.growth_clamp_upper)
        res['mean_reversion_lambda'] = (lambda x: x.to_json())(self.mean_reversion_lambda)
        res['mature_market_erp'] = (lambda x: x.to_json())(self.mature_market_erp)
        res['midcycle_window_years'] = (lambda x: x.to_json())(self.midcycle_window_years)
        res['sensitivity_steps'] = (lambda x: x.to_json())(self.sensitivity_steps)
        res['terminal_growth_rate'] = (lambda x: x.to_json())(self.terminal_growth_rate)
        res['unwired'] = (lambda x: x)(self.unwired)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Params':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class NwcXbrl:
    """Original type: nwc_xbrl = { ... }
    """

    aggregate: List[str]
    asset_components: List[str]
    liability_components: List[str]
    excluded: List[str]
    net_components: List[str] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'NwcXbrl':
        if isinstance(x, dict):
            return cls(
                aggregate=_atd_read_list(_atd_read_string)(x['aggregate']) if 'aggregate' in x else _atd_missing_json_field('NwcXbrl', 'aggregate'),
                asset_components=_atd_read_list(_atd_read_string)(x['asset_components']) if 'asset_components' in x else _atd_missing_json_field('NwcXbrl', 'asset_components'),
                liability_components=_atd_read_list(_atd_read_string)(x['liability_components']) if 'liability_components' in x else _atd_missing_json_field('NwcXbrl', 'liability_components'),
                excluded=_atd_read_list(_atd_read_string)(x['excluded']) if 'excluded' in x else _atd_missing_json_field('NwcXbrl', 'excluded'),
                net_components=_atd_read_list(_atd_read_string)(x['net_components']) if 'net_components' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('NwcXbrl', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['aggregate'] = _atd_write_list(_atd_write_string)(self.aggregate)
        res['asset_components'] = _atd_write_list(_atd_write_string)(self.asset_components)
        res['liability_components'] = _atd_write_list(_atd_write_string)(self.liability_components)
        res['excluded'] = _atd_write_list(_atd_write_string)(self.excluded)
        res['net_components'] = _atd_write_list(_atd_write_string)(self.net_components)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'NwcXbrl':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class NwcVendor:
    """Original type: nwc_vendor = { ... }
    """

    change_in_working_capital: List[str]
    sign: float
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'NwcVendor':
        if isinstance(x, dict):
            return cls(
                change_in_working_capital=_atd_read_list(_atd_read_string)(x['change_in_working_capital']) if 'change_in_working_capital' in x else _atd_missing_json_field('NwcVendor', 'change_in_working_capital'),
                sign=_atd_read_float(x['sign']) if 'sign' in x else _atd_missing_json_field('NwcVendor', 'sign'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('NwcVendor', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['change_in_working_capital'] = _atd_write_list(_atd_write_string)(self.change_in_working_capital)
        res['sign'] = _atd_write_float(self.sign)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'NwcVendor':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class NwcIfrs:
    """Original type: nwc_ifrs = { ... }
    """

    family_prefixes: List[str]
    components: List[str]
    excluded: List[str]
    sign: float
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'NwcIfrs':
        if isinstance(x, dict):
            return cls(
                family_prefixes=_atd_read_list(_atd_read_string)(x['family_prefixes']) if 'family_prefixes' in x else _atd_missing_json_field('NwcIfrs', 'family_prefixes'),
                components=_atd_read_list(_atd_read_string)(x['components']) if 'components' in x else _atd_missing_json_field('NwcIfrs', 'components'),
                excluded=_atd_read_list(_atd_read_string)(x['excluded']) if 'excluded' in x else _atd_missing_json_field('NwcIfrs', 'excluded'),
                sign=_atd_read_float(x['sign']) if 'sign' in x else _atd_missing_json_field('NwcIfrs', 'sign'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('NwcIfrs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['family_prefixes'] = _atd_write_list(_atd_write_string)(self.family_prefixes)
        res['components'] = _atd_write_list(_atd_write_string)(self.components)
        res['excluded'] = _atd_write_list(_atd_write_string)(self.excluded)
        res['sign'] = _atd_write_float(self.sign)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'NwcIfrs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class NwcDefinition:
    """Original type: nwc_definition = { ... }
    """

    name: str
    why: str
    xbrl: NwcXbrl
    ifrs: NwcIfrs
    vendor: NwcVendor

    @classmethod
    def from_json(cls, x: Any) -> 'NwcDefinition':
        if isinstance(x, dict):
            return cls(
                name=_atd_read_string(x['name']) if 'name' in x else _atd_missing_json_field('NwcDefinition', 'name'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('NwcDefinition', 'why'),
                xbrl=NwcXbrl.from_json(x['xbrl']) if 'xbrl' in x else _atd_missing_json_field('NwcDefinition', 'xbrl'),
                ifrs=NwcIfrs.from_json(x['ifrs']) if 'ifrs' in x else _atd_missing_json_field('NwcDefinition', 'ifrs'),
                vendor=NwcVendor.from_json(x['vendor']) if 'vendor' in x else _atd_missing_json_field('NwcDefinition', 'vendor'),
            )
        else:
            _atd_bad_json('NwcDefinition', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['name'] = _atd_write_string(self.name)
        res['why'] = _atd_write_string(self.why)
        res['xbrl'] = (lambda x: x.to_json())(self.xbrl)
        res['ifrs'] = (lambda x: x.to_json())(self.ifrs)
        res['vendor'] = (lambda x: x.to_json())(self.vendor)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'NwcDefinition':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Belief:
    """Original type: belief = { ... }
    """

    mean: float
    sd: float
    floor: float
    ceiling: float
    why: str
    as_of: str

    @classmethod
    def from_json(cls, x: Any) -> 'Belief':
        if isinstance(x, dict):
            return cls(
                mean=_atd_read_float(x['mean']) if 'mean' in x else _atd_missing_json_field('Belief', 'mean'),
                sd=_atd_read_float(x['sd']) if 'sd' in x else _atd_missing_json_field('Belief', 'sd'),
                floor=_atd_read_float(x['floor']) if 'floor' in x else _atd_missing_json_field('Belief', 'floor'),
                ceiling=_atd_read_float(x['ceiling']) if 'ceiling' in x else _atd_missing_json_field('Belief', 'ceiling'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('Belief', 'why'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Belief', 'as_of'),
            )
        else:
            _atd_bad_json('Belief', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['mean'] = _atd_write_float(self.mean)
        res['sd'] = _atd_write_float(self.sd)
        res['floor'] = _atd_write_float(self.floor)
        res['ceiling'] = _atd_write_float(self.ceiling)
        res['why'] = _atd_write_string(self.why)
        res['as_of'] = _atd_write_string(self.as_of)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Belief':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class NameBeliefs:
    """Original type: name_beliefs = { ... }
    """

    tickers: List[Tuple[str, Belief]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'NameBeliefs':
        if isinstance(x, dict):
            return cls(
                tickers=_atd_read_assoc_object_into_list(Belief.from_json)(x['tickers']) if 'tickers' in x else _atd_missing_json_field('NameBeliefs', 'tickers'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('NameBeliefs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['tickers'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.tickers)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'NameBeliefs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class IndustryTable:
    """Original type: industry_table = { ... }
    """

    source: str
    as_of: str
    max_age_days: int
    values: List[Tuple[str, float]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'IndustryTable':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('IndustryTable', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('IndustryTable', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('IndustryTable', 'max_age_days'),
                values=_atd_read_assoc_object_into_list(_atd_read_float)(x['values']) if 'values' in x else _atd_missing_json_field('IndustryTable', 'values'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('IndustryTable', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['values'] = _atd_write_assoc_list_to_object(_atd_write_float)(self.values)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'IndustryTable':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxSource:
    """Original type: fx_source = { ... }
    """

    series: str
    direction: str
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FxSource':
        if isinstance(x, dict):
            return cls(
                series=_atd_read_string(x['series']) if 'series' in x else _atd_missing_json_field('FxSource', 'series'),
                direction=_atd_read_string(x['direction']) if 'direction' in x else _atd_missing_json_field('FxSource', 'direction'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FxSource', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['series'] = _atd_write_string(self.series)
        res['direction'] = _atd_write_string(self.direction)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxSource':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxSources:
    """Original type: fx_sources = { ... }
    """

    source: str
    as_of: str
    max_age_days: int
    currency_countries: List[Tuple[str, str]]
    currencies: List[Tuple[str, FxSource]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FxSources':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('FxSources', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('FxSources', 'as_of'),
                max_age_days=_atd_read_int(x['max_age_days']) if 'max_age_days' in x else _atd_missing_json_field('FxSources', 'max_age_days'),
                currency_countries=_atd_read_assoc_object_into_list(_atd_read_string)(x['currency_countries']) if 'currency_countries' in x else _atd_missing_json_field('FxSources', 'currency_countries'),
                currencies=_atd_read_assoc_object_into_list(FxSource.from_json)(x['currencies']) if 'currencies' in x else _atd_missing_json_field('FxSources', 'currencies'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FxSources', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['max_age_days'] = _atd_write_int(self.max_age_days)
        res['currency_countries'] = _atd_write_assoc_list_to_object(_atd_write_string)(self.currency_countries)
        res['currencies'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.currencies)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxSources':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxRate:
    """Original type: fx_rate = { ... }
    """

    series: str
    direction: str
    as_of: str
    quoted: float
    usd_per_unit: float

    @classmethod
    def from_json(cls, x: Any) -> 'FxRate':
        if isinstance(x, dict):
            return cls(
                series=_atd_read_string(x['series']) if 'series' in x else _atd_missing_json_field('FxRate', 'series'),
                direction=_atd_read_string(x['direction']) if 'direction' in x else _atd_missing_json_field('FxRate', 'direction'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('FxRate', 'as_of'),
                quoted=_atd_read_float(x['quoted']) if 'quoted' in x else _atd_missing_json_field('FxRate', 'quoted'),
                usd_per_unit=_atd_read_float(x['usd_per_unit']) if 'usd_per_unit' in x else _atd_missing_json_field('FxRate', 'usd_per_unit'),
            )
        else:
            _atd_bad_json('FxRate', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['series'] = _atd_write_string(self.series)
        res['direction'] = _atd_write_string(self.direction)
        res['as_of'] = _atd_write_string(self.as_of)
        res['quoted'] = _atd_write_float(self.quoted)
        res['usd_per_unit'] = _atd_write_float(self.usd_per_unit)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxRate':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FxRates:
    """Original type: fx_rates = { ... }
    """

    source: str
    currencies: List[Tuple[str, FxRate]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FxRates':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('FxRates', 'source'),
                currencies=_atd_read_assoc_object_into_list(FxRate.from_json)(x['currencies']) if 'currencies' in x else _atd_missing_json_field('FxRates', 'currencies'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FxRates', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['currencies'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.currencies)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FxRates':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FfoTags:
    """Original type: ffo_tags = { ... }
    """

    net_income: List[str]
    depreciation: List[str]
    impairment: List[str]
    gains: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'FfoTags':
        if isinstance(x, dict):
            return cls(
                net_income=_atd_read_list(_atd_read_string)(x['net_income']) if 'net_income' in x else _atd_missing_json_field('FfoTags', 'net_income'),
                depreciation=_atd_read_list(_atd_read_string)(x['depreciation']) if 'depreciation' in x else _atd_missing_json_field('FfoTags', 'depreciation'),
                impairment=_atd_read_list(_atd_read_string)(x['impairment']) if 'impairment' in x else _atd_missing_json_field('FfoTags', 'impairment'),
                gains=_atd_read_list(_atd_read_string)(x['gains']) if 'gains' in x else _atd_missing_json_field('FfoTags', 'gains'),
            )
        else:
            _atd_bad_json('FfoTags', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['net_income'] = _atd_write_list(_atd_write_string)(self.net_income)
        res['depreciation'] = _atd_write_list(_atd_write_string)(self.depreciation)
        res['impairment'] = _atd_write_list(_atd_write_string)(self.impairment)
        res['gains'] = _atd_write_list(_atd_write_string)(self.gains)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FfoTags':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FfoDefinition:
    """Original type: ffo_definition = { ... }
    """

    name: str
    why: str
    xbrl: FfoTags
    ifrs: FfoTags
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FfoDefinition':
        if isinstance(x, dict):
            return cls(
                name=_atd_read_string(x['name']) if 'name' in x else _atd_missing_json_field('FfoDefinition', 'name'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('FfoDefinition', 'why'),
                xbrl=FfoTags.from_json(x['xbrl']) if 'xbrl' in x else _atd_missing_json_field('FfoDefinition', 'xbrl'),
                ifrs=FfoTags.from_json(x['ifrs']) if 'ifrs' in x else _atd_missing_json_field('FfoDefinition', 'ifrs'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FfoDefinition', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['name'] = _atd_write_string(self.name)
        res['why'] = _atd_write_string(self.why)
        res['xbrl'] = (lambda x: x.to_json())(self.xbrl)
        res['ifrs'] = (lambda x: x.to_json())(self.ifrs)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FfoDefinition':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class EbitRows:
    """Original type: ebit_rows = { ... }
    """

    operating_income: List[str]
    interest_expense: List[str]
    interest_income: List[str]
    other_nonoperating: List[str]
    equity_method: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'EbitRows':
        if isinstance(x, dict):
            return cls(
                operating_income=_atd_read_list(_atd_read_string)(x['operating_income']) if 'operating_income' in x else _atd_missing_json_field('EbitRows', 'operating_income'),
                interest_expense=_atd_read_list(_atd_read_string)(x['interest_expense']) if 'interest_expense' in x else _atd_missing_json_field('EbitRows', 'interest_expense'),
                interest_income=_atd_read_list(_atd_read_string)(x['interest_income']) if 'interest_income' in x else _atd_missing_json_field('EbitRows', 'interest_income'),
                other_nonoperating=_atd_read_list(_atd_read_string)(x['other_nonoperating']) if 'other_nonoperating' in x else _atd_missing_json_field('EbitRows', 'other_nonoperating'),
                equity_method=_atd_read_list(_atd_read_string)(x['equity_method']) if 'equity_method' in x else _atd_missing_json_field('EbitRows', 'equity_method'),
            )
        else:
            _atd_bad_json('EbitRows', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['operating_income'] = _atd_write_list(_atd_write_string)(self.operating_income)
        res['interest_expense'] = _atd_write_list(_atd_write_string)(self.interest_expense)
        res['interest_income'] = _atd_write_list(_atd_write_string)(self.interest_income)
        res['other_nonoperating'] = _atd_write_list(_atd_write_string)(self.other_nonoperating)
        res['equity_method'] = _atd_write_list(_atd_write_string)(self.equity_method)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'EbitRows':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class EbitDefinition:
    """Original type: ebit_definition = { ... }
    """

    name: str
    recipes: List[str]
    why: str
    xbrl: EbitRows
    ifrs: EbitRows
    vendor: EbitRows

    @classmethod
    def from_json(cls, x: Any) -> 'EbitDefinition':
        if isinstance(x, dict):
            return cls(
                name=_atd_read_string(x['name']) if 'name' in x else _atd_missing_json_field('EbitDefinition', 'name'),
                recipes=_atd_read_list(_atd_read_string)(x['recipes']) if 'recipes' in x else _atd_missing_json_field('EbitDefinition', 'recipes'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('EbitDefinition', 'why'),
                xbrl=EbitRows.from_json(x['xbrl']) if 'xbrl' in x else _atd_missing_json_field('EbitDefinition', 'xbrl'),
                ifrs=EbitRows.from_json(x['ifrs']) if 'ifrs' in x else _atd_missing_json_field('EbitDefinition', 'ifrs'),
                vendor=EbitRows.from_json(x['vendor']) if 'vendor' in x else _atd_missing_json_field('EbitDefinition', 'vendor'),
            )
        else:
            _atd_bad_json('EbitDefinition', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['name'] = _atd_write_string(self.name)
        res['recipes'] = _atd_write_list(_atd_write_string)(self.recipes)
        res['why'] = _atd_write_string(self.why)
        res['xbrl'] = (lambda x: x.to_json())(self.xbrl)
        res['ifrs'] = (lambda x: x.to_json())(self.ifrs)
        res['vendor'] = (lambda x: x.to_json())(self.vendor)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'EbitDefinition':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class DebtXbrl:
    """Original type: debt_xbrl = { ... }
    """

    noncurrent: List[str]
    current_total: List[str]
    current_long_term: List[str]
    short_term_borrowings: List[str]
    total_including_current: List[str]
    excluded: List[str]
    aggregate: List[str] = field(default_factory=lambda: [])
    convertible: List[str] = field(default_factory=lambda: [])
    interest_evidence: List[str] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'DebtXbrl':
        if isinstance(x, dict):
            return cls(
                noncurrent=_atd_read_list(_atd_read_string)(x['noncurrent']) if 'noncurrent' in x else _atd_missing_json_field('DebtXbrl', 'noncurrent'),
                current_total=_atd_read_list(_atd_read_string)(x['current_total']) if 'current_total' in x else _atd_missing_json_field('DebtXbrl', 'current_total'),
                current_long_term=_atd_read_list(_atd_read_string)(x['current_long_term']) if 'current_long_term' in x else _atd_missing_json_field('DebtXbrl', 'current_long_term'),
                short_term_borrowings=_atd_read_list(_atd_read_string)(x['short_term_borrowings']) if 'short_term_borrowings' in x else _atd_missing_json_field('DebtXbrl', 'short_term_borrowings'),
                total_including_current=_atd_read_list(_atd_read_string)(x['total_including_current']) if 'total_including_current' in x else _atd_missing_json_field('DebtXbrl', 'total_including_current'),
                excluded=_atd_read_list(_atd_read_string)(x['excluded']) if 'excluded' in x else _atd_missing_json_field('DebtXbrl', 'excluded'),
                aggregate=_atd_read_list(_atd_read_string)(x['aggregate']) if 'aggregate' in x else [],
                convertible=_atd_read_list(_atd_read_string)(x['convertible']) if 'convertible' in x else [],
                interest_evidence=_atd_read_list(_atd_read_string)(x['interest_evidence']) if 'interest_evidence' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('DebtXbrl', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['noncurrent'] = _atd_write_list(_atd_write_string)(self.noncurrent)
        res['current_total'] = _atd_write_list(_atd_write_string)(self.current_total)
        res['current_long_term'] = _atd_write_list(_atd_write_string)(self.current_long_term)
        res['short_term_borrowings'] = _atd_write_list(_atd_write_string)(self.short_term_borrowings)
        res['total_including_current'] = _atd_write_list(_atd_write_string)(self.total_including_current)
        res['excluded'] = _atd_write_list(_atd_write_string)(self.excluded)
        res['aggregate'] = _atd_write_list(_atd_write_string)(self.aggregate)
        res['convertible'] = _atd_write_list(_atd_write_string)(self.convertible)
        res['interest_evidence'] = _atd_write_list(_atd_write_string)(self.interest_evidence)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'DebtXbrl':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class DebtVendor:
    """Original type: debt_vendor = { ... }
    """

    long_term_debt: List[str]
    current_debt: List[str]
    current_debt_components: List[str]
    not_used: List[str] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'DebtVendor':
        if isinstance(x, dict):
            return cls(
                long_term_debt=_atd_read_list(_atd_read_string)(x['long_term_debt']) if 'long_term_debt' in x else _atd_missing_json_field('DebtVendor', 'long_term_debt'),
                current_debt=_atd_read_list(_atd_read_string)(x['current_debt']) if 'current_debt' in x else _atd_missing_json_field('DebtVendor', 'current_debt'),
                current_debt_components=_atd_read_list(_atd_read_string)(x['current_debt_components']) if 'current_debt_components' in x else _atd_missing_json_field('DebtVendor', 'current_debt_components'),
                not_used=_atd_read_list(_atd_read_string)(x['not_used']) if 'not_used' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('DebtVendor', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['long_term_debt'] = _atd_write_list(_atd_write_string)(self.long_term_debt)
        res['current_debt'] = _atd_write_list(_atd_write_string)(self.current_debt)
        res['current_debt_components'] = _atd_write_list(_atd_write_string)(self.current_debt_components)
        res['not_used'] = _atd_write_list(_atd_write_string)(self.not_used)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'DebtVendor':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class DebtIfrs:
    """Original type: debt_ifrs = { ... }
    """

    total: List[str]
    noncurrent_borrowings: List[str]
    noncurrent_bonds: List[str]
    current_bonds: List[str]
    current_total: List[str]
    short_term_borrowings: List[str]
    current_portion_of_long_term: List[str]
    excluded: List[str]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'DebtIfrs':
        if isinstance(x, dict):
            return cls(
                total=_atd_read_list(_atd_read_string)(x['total']) if 'total' in x else _atd_missing_json_field('DebtIfrs', 'total'),
                noncurrent_borrowings=_atd_read_list(_atd_read_string)(x['noncurrent_borrowings']) if 'noncurrent_borrowings' in x else _atd_missing_json_field('DebtIfrs', 'noncurrent_borrowings'),
                noncurrent_bonds=_atd_read_list(_atd_read_string)(x['noncurrent_bonds']) if 'noncurrent_bonds' in x else _atd_missing_json_field('DebtIfrs', 'noncurrent_bonds'),
                current_bonds=_atd_read_list(_atd_read_string)(x['current_bonds']) if 'current_bonds' in x else _atd_missing_json_field('DebtIfrs', 'current_bonds'),
                current_total=_atd_read_list(_atd_read_string)(x['current_total']) if 'current_total' in x else _atd_missing_json_field('DebtIfrs', 'current_total'),
                short_term_borrowings=_atd_read_list(_atd_read_string)(x['short_term_borrowings']) if 'short_term_borrowings' in x else _atd_missing_json_field('DebtIfrs', 'short_term_borrowings'),
                current_portion_of_long_term=_atd_read_list(_atd_read_string)(x['current_portion_of_long_term']) if 'current_portion_of_long_term' in x else _atd_missing_json_field('DebtIfrs', 'current_portion_of_long_term'),
                excluded=_atd_read_list(_atd_read_string)(x['excluded']) if 'excluded' in x else _atd_missing_json_field('DebtIfrs', 'excluded'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('DebtIfrs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['total'] = _atd_write_list(_atd_write_string)(self.total)
        res['noncurrent_borrowings'] = _atd_write_list(_atd_write_string)(self.noncurrent_borrowings)
        res['noncurrent_bonds'] = _atd_write_list(_atd_write_string)(self.noncurrent_bonds)
        res['current_bonds'] = _atd_write_list(_atd_write_string)(self.current_bonds)
        res['current_total'] = _atd_write_list(_atd_write_string)(self.current_total)
        res['short_term_borrowings'] = _atd_write_list(_atd_write_string)(self.short_term_borrowings)
        res['current_portion_of_long_term'] = _atd_write_list(_atd_write_string)(self.current_portion_of_long_term)
        res['excluded'] = _atd_write_list(_atd_write_string)(self.excluded)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'DebtIfrs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class DebtDefinition:
    """Original type: debt_definition = { ... }
    """

    name: str
    why: str
    xbrl: DebtXbrl
    ifrs: DebtIfrs
    vendor: DebtVendor

    @classmethod
    def from_json(cls, x: Any) -> 'DebtDefinition':
        if isinstance(x, dict):
            return cls(
                name=_atd_read_string(x['name']) if 'name' in x else _atd_missing_json_field('DebtDefinition', 'name'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('DebtDefinition', 'why'),
                xbrl=DebtXbrl.from_json(x['xbrl']) if 'xbrl' in x else _atd_missing_json_field('DebtDefinition', 'xbrl'),
                ifrs=DebtIfrs.from_json(x['ifrs']) if 'ifrs' in x else _atd_missing_json_field('DebtDefinition', 'ifrs'),
                vendor=DebtVendor.from_json(x['vendor']) if 'vendor' in x else _atd_missing_json_field('DebtDefinition', 'vendor'),
            )
        else:
            _atd_bad_json('DebtDefinition', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['name'] = _atd_write_string(self.name)
        res['why'] = _atd_write_string(self.why)
        res['xbrl'] = (lambda x: x.to_json())(self.xbrl)
        res['ifrs'] = (lambda x: x.to_json())(self.ifrs)
        res['vendor'] = (lambda x: x.to_json())(self.vendor)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'DebtDefinition':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class CashXbrl:
    """Original type: cash_xbrl = { ... }
    """

    cash_equivalents: List[str]
    restricted_inclusive: List[str]
    restricted_cash: List[List[str]]
    short_term_investments: List[str]

    @classmethod
    def from_json(cls, x: Any) -> 'CashXbrl':
        if isinstance(x, dict):
            return cls(
                cash_equivalents=_atd_read_list(_atd_read_string)(x['cash_equivalents']) if 'cash_equivalents' in x else _atd_missing_json_field('CashXbrl', 'cash_equivalents'),
                restricted_inclusive=_atd_read_list(_atd_read_string)(x['restricted_inclusive']) if 'restricted_inclusive' in x else _atd_missing_json_field('CashXbrl', 'restricted_inclusive'),
                restricted_cash=_atd_read_list(_atd_read_list(_atd_read_string))(x['restricted_cash']) if 'restricted_cash' in x else _atd_missing_json_field('CashXbrl', 'restricted_cash'),
                short_term_investments=_atd_read_list(_atd_read_string)(x['short_term_investments']) if 'short_term_investments' in x else _atd_missing_json_field('CashXbrl', 'short_term_investments'),
            )
        else:
            _atd_bad_json('CashXbrl', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['cash_equivalents'] = _atd_write_list(_atd_write_string)(self.cash_equivalents)
        res['restricted_inclusive'] = _atd_write_list(_atd_write_string)(self.restricted_inclusive)
        res['restricted_cash'] = _atd_write_list(_atd_write_list(_atd_write_string))(self.restricted_cash)
        res['short_term_investments'] = _atd_write_list(_atd_write_string)(self.short_term_investments)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'CashXbrl':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class CashVendor:
    """Original type: cash_vendor = { ... }
    """

    cash_equivalents: List[str]
    short_term_investments: List[str]
    not_used: List[str] = field(default_factory=lambda: [])
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'CashVendor':
        if isinstance(x, dict):
            return cls(
                cash_equivalents=_atd_read_list(_atd_read_string)(x['cash_equivalents']) if 'cash_equivalents' in x else _atd_missing_json_field('CashVendor', 'cash_equivalents'),
                short_term_investments=_atd_read_list(_atd_read_string)(x['short_term_investments']) if 'short_term_investments' in x else _atd_missing_json_field('CashVendor', 'short_term_investments'),
                not_used=_atd_read_list(_atd_read_string)(x['not_used']) if 'not_used' in x else [],
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('CashVendor', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['cash_equivalents'] = _atd_write_list(_atd_write_string)(self.cash_equivalents)
        res['short_term_investments'] = _atd_write_list(_atd_write_string)(self.short_term_investments)
        res['not_used'] = _atd_write_list(_atd_write_string)(self.not_used)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'CashVendor':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class CashIfrs:
    """Original type: cash_ifrs = { ... }
    """

    cash_equivalents: List[str]
    short_term_investments: List[List[str]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'CashIfrs':
        if isinstance(x, dict):
            return cls(
                cash_equivalents=_atd_read_list(_atd_read_string)(x['cash_equivalents']) if 'cash_equivalents' in x else _atd_missing_json_field('CashIfrs', 'cash_equivalents'),
                short_term_investments=_atd_read_list(_atd_read_list(_atd_read_string))(x['short_term_investments']) if 'short_term_investments' in x else _atd_missing_json_field('CashIfrs', 'short_term_investments'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('CashIfrs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['cash_equivalents'] = _atd_write_list(_atd_write_string)(self.cash_equivalents)
        res['short_term_investments'] = _atd_write_list(_atd_write_list(_atd_write_string))(self.short_term_investments)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'CashIfrs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class CashDefinition:
    """Original type: cash_definition = { ... }
    """

    name: str
    why: str
    xbrl: CashXbrl
    ifrs: CashIfrs
    vendor: CashVendor

    @classmethod
    def from_json(cls, x: Any) -> 'CashDefinition':
        if isinstance(x, dict):
            return cls(
                name=_atd_read_string(x['name']) if 'name' in x else _atd_missing_json_field('CashDefinition', 'name'),
                why=_atd_read_string(x['why']) if 'why' in x else _atd_missing_json_field('CashDefinition', 'why'),
                xbrl=CashXbrl.from_json(x['xbrl']) if 'xbrl' in x else _atd_missing_json_field('CashDefinition', 'xbrl'),
                ifrs=CashIfrs.from_json(x['ifrs']) if 'ifrs' in x else _atd_missing_json_field('CashDefinition', 'ifrs'),
                vendor=CashVendor.from_json(x['vendor']) if 'vendor' in x else _atd_missing_json_field('CashDefinition', 'vendor'),
            )
        else:
            _atd_bad_json('CashDefinition', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['name'] = _atd_write_string(self.name)
        res['why'] = _atd_write_string(self.why)
        res['xbrl'] = (lambda x: x.to_json())(self.xbrl)
        res['ifrs'] = (lambda x: x.to_json())(self.ifrs)
        res['vendor'] = (lambda x: x.to_json())(self.vendor)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'CashDefinition':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FieldDefinitions:
    """Original type: field_definitions = { ... }
    """

    source: str
    as_of: str
    cash: CashDefinition
    total_debt: DebtDefinition
    delta_nwc: NwcDefinition
    ebit: EbitDefinition
    ffo: FfoDefinition
    shares_for_flows: SharesForFlows
    shares_for_market_cap: SharesForMarketCap
    refinement_policy: RefinementPolicy
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'FieldDefinitions':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('FieldDefinitions', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('FieldDefinitions', 'as_of'),
                cash=CashDefinition.from_json(x['cash']) if 'cash' in x else _atd_missing_json_field('FieldDefinitions', 'cash'),
                total_debt=DebtDefinition.from_json(x['total_debt']) if 'total_debt' in x else _atd_missing_json_field('FieldDefinitions', 'total_debt'),
                delta_nwc=NwcDefinition.from_json(x['delta_nwc']) if 'delta_nwc' in x else _atd_missing_json_field('FieldDefinitions', 'delta_nwc'),
                ebit=EbitDefinition.from_json(x['ebit']) if 'ebit' in x else _atd_missing_json_field('FieldDefinitions', 'ebit'),
                ffo=FfoDefinition.from_json(x['ffo']) if 'ffo' in x else _atd_missing_json_field('FieldDefinitions', 'ffo'),
                shares_for_flows=SharesForFlows.from_json(x['shares_for_flows']) if 'shares_for_flows' in x else _atd_missing_json_field('FieldDefinitions', 'shares_for_flows'),
                shares_for_market_cap=SharesForMarketCap.from_json(x['shares_for_market_cap']) if 'shares_for_market_cap' in x else _atd_missing_json_field('FieldDefinitions', 'shares_for_market_cap'),
                refinement_policy=RefinementPolicy.from_json(x['refinement_policy']) if 'refinement_policy' in x else _atd_missing_json_field('FieldDefinitions', 'refinement_policy'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('FieldDefinitions', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['cash'] = (lambda x: x.to_json())(self.cash)
        res['total_debt'] = (lambda x: x.to_json())(self.total_debt)
        res['delta_nwc'] = (lambda x: x.to_json())(self.delta_nwc)
        res['ebit'] = (lambda x: x.to_json())(self.ebit)
        res['ffo'] = (lambda x: x.to_json())(self.ffo)
        res['shares_for_flows'] = (lambda x: x.to_json())(self.shares_for_flows)
        res['shares_for_market_cap'] = (lambda x: x.to_json())(self.shares_for_market_cap)
        res['refinement_policy'] = (lambda x: x.to_json())(self.refinement_policy)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'FieldDefinitions':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ClassRule:
    """Original type: class_rule = { ... }
    """

    lens: str
    admissible_models: List[str]
    never: str
    floor_basis_default: str
    scope_limits_default: List[str] = field(default_factory=lambda: [])
    floor_present_default: Optional[bool] = field(default_factory=lambda: None)

    @classmethod
    def from_json(cls, x: Any) -> 'ClassRule':
        if isinstance(x, dict):
            return cls(
                lens=_atd_read_string(x['lens']) if 'lens' in x else _atd_missing_json_field('ClassRule', 'lens'),
                admissible_models=_atd_read_list(_atd_read_string)(x['admissible_models']) if 'admissible_models' in x else _atd_missing_json_field('ClassRule', 'admissible_models'),
                never=_atd_read_string(x['never']) if 'never' in x else _atd_missing_json_field('ClassRule', 'never'),
                floor_basis_default=_atd_read_string(x['floor_basis_default']) if 'floor_basis_default' in x else _atd_missing_json_field('ClassRule', 'floor_basis_default'),
                scope_limits_default=_atd_read_list(_atd_read_string)(x['scope_limits_default']) if 'scope_limits_default' in x else [],
                floor_present_default=_atd_read_nullable(_atd_read_bool)(x['floor_present_default']) if 'floor_present_default' in x else None,
            )
        else:
            _atd_bad_json('ClassRule', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['lens'] = _atd_write_string(self.lens)
        res['admissible_models'] = _atd_write_list(_atd_write_string)(self.admissible_models)
        res['never'] = _atd_write_string(self.never)
        res['floor_basis_default'] = _atd_write_string(self.floor_basis_default)
        res['scope_limits_default'] = _atd_write_list(_atd_write_string)(self.scope_limits_default)
        res['floor_present_default'] = _atd_write_nullable(_atd_write_bool)(self.floor_present_default)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'ClassRule':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ClassBeliefs:
    """Original type: class_beliefs = { ... }
    """

    classes: List[Tuple[str, Belief]]
    notes: List[str] = field(default_factory=lambda: [])
    names: List[Tuple[str, Belief]] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'ClassBeliefs':
        if isinstance(x, dict):
            return cls(
                classes=_atd_read_assoc_object_into_list(Belief.from_json)(x['classes']) if 'classes' in x else _atd_missing_json_field('ClassBeliefs', 'classes'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
                names=_atd_read_assoc_object_into_list(Belief.from_json)(x['names']) if 'names' in x else [],
            )
        else:
            _atd_bad_json('ClassBeliefs', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['classes'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.classes)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        res['names'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.names)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'ClassBeliefs':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Admissibility:
    """Original type: admissibility = { ... }
    """

    source: str
    as_of: str
    classes: List[Tuple[str, ClassRule]]
    notes: List[str] = field(default_factory=lambda: [])

    @classmethod
    def from_json(cls, x: Any) -> 'Admissibility':
        if isinstance(x, dict):
            return cls(
                source=_atd_read_string(x['source']) if 'source' in x else _atd_missing_json_field('Admissibility', 'source'),
                as_of=_atd_read_string(x['as_of']) if 'as_of' in x else _atd_missing_json_field('Admissibility', 'as_of'),
                classes=_atd_read_assoc_object_into_list(ClassRule.from_json)(x['classes']) if 'classes' in x else _atd_missing_json_field('Admissibility', 'classes'),
                notes=_atd_read_list(_atd_read_string)(x['notes']) if 'notes' in x else [],
            )
        else:
            _atd_bad_json('Admissibility', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['source'] = _atd_write_string(self.source)
        res['as_of'] = _atd_write_string(self.as_of)
        res['classes'] = _atd_write_assoc_list_to_object((lambda x: x.to_json()))(self.classes)
        res['notes'] = _atd_write_list(_atd_write_string)(self.notes)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Admissibility':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)
